-- ==========================================
-- 1. Create Tables
-- ==========================================

-- Profiles (linked to auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null check (role in ('admin', 'user')),
  full_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inventory
create table public.inventory (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('manufactured', 'resell', 'waste')),
  quantity integer not null default 0,
  price_per_cube numeric(10, 2),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Customers
create table public.customers (
  id bigint generated by default as identity primary key,
  customer_code text not null unique,
  name text not null,
  whatsapp_number text not null unique,
  address text default '',
  email text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sales
create table public.sales (
  id bigint generated by default as identity primary key,
  sale_code text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  quantity integer not null,
  price_per_cube numeric(10, 2) not null,
  total_amount numeric(10, 2) not null,
  payment_type text not null check (payment_type in ('cash', 'debt')),
  bill_pdf_url text,
  sale_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text not null
);

-- Debts
create table public.debts (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  total_amount numeric(10, 2) not null,
  paid_amount numeric(10, 2) not null default 0,
  remaining_amount numeric(10, 2) not null,
  status text not null check (status in ('pending', 'partial', 'settled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Debt Settlements
create table public.debt_settlements (
  id bigint generated by default as identity primary key,
  debt_id bigint references public.debts(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  amount_paid numeric(10, 2) not null,
  settlement_date timestamp with time zone default timezone('utc'::text, now()) not null,
  bill_pdf_url text,
  created_by text not null
);

-- Settings
create table public.settings (
  id bigint generated by default as identity primary key,
  company_name text not null default 'Sagacious Ice Factory',
  company_address text default '',
  company_phone text default '',
  company_email text default '',
  logo_url text,
  favicon_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 2. Seed Initial Data
-- ==========================================

insert into public.inventory (code, type, quantity, price_per_cube) values
('MFC-0001', 'manufactured', 2450, 12.00),
('RSC-0001', 'resell', 1100, 18.50),
('WST-0001', 'waste', 120, null)
on conflict (code) do nothing;

insert into public.settings (company_name, company_address, company_phone, company_email) values
('Sagacious Ice Factory', '102 Industrial Zone, Colombo, Sri Lanka', '0771234567', 'info@sagaciousice.com')
on conflict do nothing;

-- ==========================================
-- 3. Enable Row Level Security (RLS)
-- ==========================================

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.debts enable row level security;
alter table public.debt_settlements enable row level security;
alter table public.settings enable row level security;

-- ==========================================
-- 4. Create Helper Functions for Policies
-- ==========================================

-- Check if current user is an admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- ==========================================
-- 5. RLS Policies Definition
-- ==========================================

-- Profiles policies
create policy "Allow read profiles for authenticated" on public.profiles
  for select to authenticated using (true);

create policy "Allow update profiles for admins" on public.profiles
  for update to authenticated using (public.is_admin());

-- Inventory policies
create policy "Allow read inventory for authenticated" on public.inventory
  for select to authenticated using (true);

create policy "Allow write inventory for admins" on public.inventory
  for all to authenticated using (public.is_admin());

-- Settings policies
create policy "Allow read settings for authenticated" on public.settings
  for select to authenticated using (true);

create policy "Allow write settings for admins" on public.settings
  for all to authenticated using (public.is_admin());

-- Customers policies
create policy "Allow read customers for authenticated" on public.customers
  for select to authenticated using (true);

create policy "Allow write customers for authenticated" on public.customers
  for all to authenticated using (true);

-- Sales policies
create policy "Allow read sales for authenticated" on public.sales
  for select to authenticated using (true);

create policy "Allow write sales for authenticated" on public.sales
  for all to authenticated using (true);

-- Debts policies
create policy "Allow read debts for authenticated" on public.debts
  for select to authenticated using (true);

create policy "Allow write debts for authenticated" on public.debts
  for all to authenticated using (true);

-- Debt Settlements policies
create policy "Allow read settlements for authenticated" on public.debt_settlements
  for select to authenticated using (true);

create policy "Allow write settlements for authenticated" on public.debt_settlements
  for all to authenticated using (true);

-- ==========================================
-- 6. Trigger to Create Profile on User Signup
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce(new.raw_user_meta_data->>'role', 'user')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 7. Enable Supabase Realtime for Tables
-- ==========================================

alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.inventory;
alter publication supabase_realtime add table public.customers;
alter publication supabase_realtime add table public.sales;
alter publication supabase_realtime add table public.debts;
alter publication supabase_realtime add table public.debt_settlements;
alter publication supabase_realtime add table public.settings;

