-- ==========================================
-- 1. Create Tables
-- ==========================================

-- Profiles (linked to auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null check (role in ('admin', 'user')),
  full_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inventory
create table public.inventory (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('manufactured', 'resell', 'waste')),
  quantity integer not null default 0,
  price_per_cube numeric(10, 2),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Customers
create table public.customers (
  id bigint generated by default as identity primary key,
  customer_code text not null unique,
  name text not null,
  whatsapp_number text unique,
  contact_number text,
  address text default '',
  is_branch boolean not null default false,
  notes text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint customers_has_a_number check (whatsapp_number is not null or contact_number is not null)
);

-- Sales
-- cube_type/price_per_cube are nullable: populated only when the whole
-- order reduces to exactly one (cube_type, price_per_cube) pair across all
-- its items (the common single-item case); null when an order mixes cube
-- types or per-row rates. quantity is always the sum across items. See
-- sale_items below for the per-order line items.
create table public.sales (
  id bigint generated by default as identity primary key,
  sale_code text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  cube_type text check (cube_type in ('manufactured', 'resell')),
  quantity integer not null,
  price_per_cube numeric(10, 2),
  total_amount numeric(10, 2) not null,
  payment_type text not null check (payment_type in ('cash', 'debt')),
  bill_pdf_url text,
  sale_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text not null
);

-- Sale Line Items — one order (one sale_code/one bill) can contain multiple
-- cube types, each its own row here.
create table public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  quantity integer not null check (quantity > 0),
  price_per_cube numeric(10, 2) not null check (price_per_cube > 0),
  subtotal numeric(10, 2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_sale_items_sale_id on public.sale_items(sale_id);

-- Debts
create table public.debts (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  total_amount numeric(10, 2) not null,
  paid_amount numeric(10, 2) not null default 0,
  remaining_amount numeric(10, 2) not null,
  status text not null check (status in ('pending', 'partial', 'settled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Debt Settlements
create table public.debt_settlements (
  id bigint generated by default as identity primary key,
  debt_id bigint references public.debts(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  amount_paid numeric(10, 2) not null,
  payment_method text not null default 'cash' check (payment_method in ('cash', 'bank_transfer', 'cheque', 'other', 'card')),
  notes text,
  settlement_date timestamp with time zone default timezone('utc'::text, now()) not null,
  bill_pdf_url text,
  created_by text not null
);

-- Settings
create table public.settings (
  id bigint generated by default as identity primary key,
  company_name text not null default 'Sagacious Ice Factory',
  company_address text default '',
  company_phone text default '',
  company_email text default '',
  logo_url text,
  favicon_url text,
  gemini_api_key text default '',
  ai_enabled boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Code Counters (Atomic Sequential Code Generator)
create table if not exists public.code_counters (
  entity text primary key,
  last_value bigint not null default 0
);

-- Inventory Transactions Audit Log
create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  inventory_id bigint references public.inventory(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('add', 'sale_deduction', 'manual_removal', 'adjustment')),
  quantity_change integer not null,
  previous_quantity integer not null,
  new_quantity integer not null,
  reference_code text default '',
  created_by text default 'System',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Vehicles
create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_no text not null unique,
  vehicle_model text not null,
  vehicle_type text not null check (vehicle_type in ('lorry', 'pickup')),
  initial_odometer integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Vehicle Trip History Log
create table if not exists public.vehicle_trips (
  id bigint generated by default as identity primary key,
  vehicle_id bigint references public.vehicles(id) on delete cascade,
  trip_date date not null default (timezone('utc'::text, now()))::date,
  start_odometer integer not null,
  end_odometer integer not null,
  distance_travelled integer generated always as (end_odometer - start_odometer) stored,
  description text default '',
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint vehicle_trips_odometer_order check (end_odometer >= start_odometer)
);

-- Employees
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  employee_code text not null unique,
  name text not null,
  nic text not null unique,
  phone text default '',
  address text default '',
  job_type text default '',
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Employee Attendance Log
create table if not exists public.employee_attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  attendance_date date not null default (timezone('utc'::text, now()))::date,
  start_time time,
  end_time time,
  description text default '',
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_employee_attendance_employee_id on public.employee_attendance(employee_id);
create index if not exists idx_employee_attendance_date on public.employee_attendance(attendance_date);

-- Transport Trip Log (driver is any employee, per TransportTab.md's
-- "Driver: (linked to employee tab)")
create table if not exists public.transport_trips (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  employee_id bigint not null references public.employees(id) on delete restrict,
  start_odometer integer not null,
  end_odometer integer,
  distance_travelled integer generated always as (
    case when end_odometer is not null then end_odometer - start_odometer else null end
  ) stored,
  start_datetime timestamp with time zone not null default now(),
  end_datetime timestamp with time zone,
  description text default '',
  end_description text default '',
  status text not null default 'ongoing' check (status in ('ongoing', 'completed')),
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint transport_trips_odometer_order check (end_odometer is null or end_odometer >= start_odometer)
);

create index if not exists idx_transport_trips_vehicle_id on public.transport_trips(vehicle_id);
create index if not exists idx_transport_trips_employee_id on public.transport_trips(employee_id);
create index if not exists idx_transport_trips_status on public.transport_trips(status);
create index if not exists idx_transport_trips_start_datetime on public.transport_trips(start_datetime);

-- Per-customer custom cube prices. New Order checkout looks up a rate here
-- for the selected customer + cube type first; falls back to the live
-- inventory.price_per_cube when no override row exists for that pair.
create table if not exists public.customer_cube_prices (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  price_per_cube numeric(10, 2) not null check (price_per_cube > 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint customer_cube_prices_customer_type_unique unique (customer_id, cube_type)
);

create index if not exists idx_customer_cube_prices_customer_id on public.customer_cube_prices(customer_id);

-- ==========================================
-- 2. Seed Initial Data & Indexes
-- ==========================================

insert into public.inventory (code, type, quantity, price_per_cube) values
('MFC-0001', 'manufactured', 2450, 12.00),
('RSC-0001', 'resell', 1100, 18.50),
('BNC-0001', 'waste', 120, null)
on conflict (code) do nothing;

insert into public.settings (company_name, company_address, company_phone, company_email) values
('Sagacious Ice Factory', '102 Industrial Zone, Colombo, Sri Lanka', '0771234567', 'info@sagaciousice.com')
on conflict do nothing;

insert into public.code_counters (entity, last_value) values
('sale', 0),
('customer', 0),
('settlement', 0)
on conflict (entity) do nothing;

-- Performance Database Indexes
create index if not exists idx_sales_customer_id on public.sales(customer_id);
create index if not exists idx_sales_sale_date on public.sales(sale_date);
create index if not exists idx_sales_payment_type on public.sales(payment_type);
create index if not exists idx_debts_customer_id on public.debts(customer_id);
create index if not exists idx_debts_status on public.debts(status);
create index if not exists idx_debt_settlements_debt_id on public.debt_settlements(debt_id);
create index if not exists idx_debt_settlements_customer_id on public.debt_settlements(customer_id);
create index if not exists idx_customers_whatsapp on public.customers(whatsapp_number);
create index if not exists idx_operating_expenses_category on public.operating_expenses(category);
create index if not exists idx_operating_expenses_date on public.operating_expenses(expense_date);
create index if not exists idx_inventory_transactions_inv_id on public.inventory_transactions(inventory_id);
create index if not exists idx_vehicle_trips_vehicle_id on public.vehicle_trips(vehicle_id);
create index if not exists idx_vehicle_trips_trip_date on public.vehicle_trips(trip_date);

-- ==========================================
-- 3. Enable Row Level Security (RLS)
-- ==========================================

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.debts enable row level security;
alter table public.debt_settlements enable row level security;
alter table public.settings enable row level security;
alter table public.code_counters enable row level security;
alter table public.inventory_transactions enable row level security;
alter table public.vehicles enable row level security;
alter table public.vehicle_trips enable row level security;
alter table public.employees enable row level security;
alter table public.employee_attendance enable row level security;
alter table public.transport_trips enable row level security;
alter table public.customer_cube_prices enable row level security;

-- ==========================================
-- 4. Create Helper & Atomic RPC Functions
-- ==========================================

-- Check if current user is an admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Atomic Sequential Code Generator
create or replace function public.get_next_code(p_entity text, p_prefix text)
returns text as $$
declare
  v_next bigint;
  v_date_suffix text;
begin
  insert into public.code_counters (entity, last_value)
  values (p_entity, 1)
  on conflict (entity) do update set last_value = public.code_counters.last_value + 1
  returning last_value into v_next;

  if p_entity = 'customer' then
    return p_prefix || '-' || lpad(v_next::text, 4, '0');
  elsif p_entity in ('expense_category', 'expense_item') then
    return p_prefix || '-' || lpad(v_next::text, 5, '0');
  else
    v_date_suffix := to_char(now(), 'DDMMYY');
    return p_prefix || '-' || v_next::text || '-' || v_date_suffix;
  end if;
end;
$$ language plpgsql security definer;

-- Atomic Inventory Add Stock
create or replace function public.add_inventory_stock(p_id bigint, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_prev_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select quantity into v_prev_qty
  from public.inventory
  where id = p_id
  for update;

  if not found then
    raise exception 'Inventory item not found';
  end if;

  v_new_qty := v_prev_qty + p_amount;
  
  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = p_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (p_id, 'add', p_amount, v_prev_qty, v_new_qty, 'STOCK_ADD', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Deduct Stock (By Item ID)
create or replace function public.deduct_inventory_stock(p_id bigint, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select quantity into v_current_qty
  from public.inventory
  where id = p_id
  for update;

  if not found then
    raise exception 'Inventory item not found';
  end if;

  if v_current_qty < p_amount then
    raise exception 'Insufficient stock. Available: %', v_current_qty;
  end if;

  v_new_qty := v_current_qty - p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = p_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (p_id, 'manual_removal', -p_amount, v_current_qty, v_new_qty, 'MANUAL_REMOVE', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Add Stock (By Cube Type)
-- Row-locked mirror of deduct_inventory_stock_by_type, used wherever stock is
-- added by cube type rather than by a known inventory row id (e.g. rolling
-- back a sale's stock deduction when the debt record insert fails). Prevents
-- the lost-update race where two concurrent adds both read the same starting
-- quantity.
create or replace function public.add_inventory_stock_by_type(p_cube_type text, p_amount integer, p_reference_code text default 'STOCK_ADD', p_created_by text default 'Operator')
returns void as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select id, quantity into v_item_id, v_current_qty
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then
    raise exception 'Inventory item for % not found', p_cube_type;
  end if;

  v_new_qty := v_current_qty + p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = v_item_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (v_item_id, 'add', p_amount, v_current_qty, v_new_qty, p_reference_code, p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Deduct Stock (By Cube Type)
create or replace function public.deduct_inventory_stock_by_type(p_cube_type text, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select id, quantity into v_item_id, v_current_qty
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then
    raise exception 'Inventory item for % not found', p_cube_type;
  end if;

  if v_current_qty < p_amount then
    raise exception 'Insufficient stock. Available: %', v_current_qty;
  end if;

  v_new_qty := v_current_qty - p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = v_item_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (v_item_id, 'sale_deduction', -p_amount, v_current_qty, v_new_qty, 'SALE_DEDUCTION', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Transactional Order Placement Function
-- SECURITY NOTE: the sale price is never trusted from the client. It is always
-- read from the locked inventory row; a caller-supplied price is only honored
-- when the caller is an admin (Key Business Rule: "price per cube editable by
-- admin only"). This closes the gap where a non-admin (or a direct RPC call)
-- could previously submit an arbitrary price_per_cube and have it accepted.
--
-- CASH-TO-OLD-DEBT OFFSET (debtsLogic.md rules):
--   CASH order: the cash amount (= new order total) is applied FIFO against
--   any pre-existing outstanding debts for this customer. Each old debt is
--   reduced/settled in order. If an old debt is only partially cleared, its
--   created_at is refreshed to today so its aging clock resets. The new sale
--   itself is always recorded as payment_type='cash' — no new debt is created
--   for this sale regardless of whether any old debt still remains.
--
--   DEBT CREDIT order: unaffected — a new debt record is created for this
--   sale exactly as before; old debts are not touched.
--
-- Example: customer owes 50,000 (old debt). Places a new 20,000 cash order.
-- The 20,000 cash is applied to the old debt -> old debt drops to 30,000 and
-- its date is refreshed to today. New sale is recorded as cash (fully paid
-- from this transaction's perspective). Total outstanding remains 30,000.
create or replace function public.place_order_transaction(
  p_customer_id bigint,
  p_cube_type text,
  p_quantity integer,
  p_price_per_cube numeric,
  p_payment_type text,
  p_created_by text
) returns jsonb as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_inventory_price numeric(10, 2);
  v_final_price numeric(10, 2);
  v_new_qty integer;
  v_sale_code text;
  v_total_amount numeric(10, 2);
  v_sale_id bigint;
  v_debt_id bigint := null;
  v_now timestamp with time zone := timezone('utc'::text, now());
  v_cash_remaining numeric(10, 2);
  v_applied_to_old_debt numeric(10, 2) := 0;
  v_old_debt record;
  v_apply_amt numeric(10, 2);
  v_old_new_remaining numeric(10, 2);
  v_old_new_status text;
begin
  -- Validate inputs
  if p_customer_id is null then raise exception 'Customer is required'; end if;
  if p_quantity <= 0 then raise exception 'Quantity must be a positive integer'; end if;
  if p_payment_type not in ('cash', 'debt') then raise exception 'Invalid payment type'; end if;

  -- 1. Lock inventory row and read the authoritative price + stock
  select id, quantity, price_per_cube into v_item_id, v_current_qty, v_inventory_price
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then raise exception 'Inventory item for % not found', p_cube_type; end if;
  if v_current_qty < p_quantity then raise exception 'Insufficient stock. Available: %', v_current_qty; end if;
  if v_inventory_price is null or v_inventory_price <= 0 then
    raise exception 'Price per cube must be set before placing a sale';
  end if;

  -- Non-admins (and any caller not supplying a price) always sell at the
  -- current inventory price. Admins may override with a caller-supplied
  -- positive price (e.g. a negotiated discount).
  if public.is_admin() and p_price_per_cube is not null and p_price_per_cube > 0 then
    v_final_price := p_price_per_cube;
  else
    v_final_price := v_inventory_price;
  end if;

  v_new_qty := v_current_qty - p_quantity;

  -- 2. Deduct inventory stock
  update public.inventory
  set quantity = v_new_qty,
      updated_at = v_now
  where id = v_item_id;

  -- 3. Atomic sale code generation
  v_sale_code := public.get_next_code('sale', 'S');
  v_total_amount := v_final_price * p_quantity;

  -- 4. Cash-to-old-debt FIFO offset (cash orders only)
  -- The new order's cash is applied against old outstanding debts oldest-first.
  -- Any old debt that is only partially cleared has its created_at reset to
  -- today so its aging clock restarts. The new sale itself always stays 'cash'.
  if p_payment_type = 'cash' then
    v_cash_remaining := v_total_amount;

    for v_old_debt in
      select id, remaining_amount
      from public.debts
      where customer_id = p_customer_id
        and status in ('pending', 'partial')
      order by created_at asc
      for update
    loop
      exit when v_cash_remaining <= 0;

      v_apply_amt := least(v_cash_remaining, v_old_debt.remaining_amount);
      v_old_new_remaining := v_old_debt.remaining_amount - v_apply_amt;
      v_old_new_status := case when v_old_new_remaining <= 0 then 'settled' else 'partial' end;

      -- Update the old debt; if it still has a remaining balance, refresh its
      -- created_at to today so the aging clock resets on the outstanding amount.
      update public.debts
      set paid_amount     = paid_amount + v_apply_amt,
          remaining_amount = v_old_new_remaining,
          status          = v_old_new_status,
          created_at      = case when v_old_new_remaining > 0 then v_now else created_at end
      where id = v_old_debt.id;

      insert into public.debt_settlements (debt_id, customer_id, amount_paid, settlement_date, created_by)
      values (v_old_debt.id, p_customer_id, v_apply_amt, v_now,
              p_created_by || ' (auto-applied from sale ' || v_sale_code || ')');

      v_applied_to_old_debt := v_applied_to_old_debt + v_apply_amt;
      v_cash_remaining := v_cash_remaining - v_apply_amt;
    end loop;
  end if;

  -- 5. Create sale record (payment_type is always what the operator selected)
  insert into public.sales (
    sale_code, customer_id, cube_type, quantity, price_per_cube, total_amount, payment_type, sale_date, created_by
  ) values (
    v_sale_code, p_customer_id, p_cube_type, p_quantity, v_final_price, v_total_amount, p_payment_type, v_now, p_created_by
  ) returning id into v_sale_id;

  -- 6. Record inventory audit log
  insert into public.inventory_transactions (
    inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by
  ) values (
    v_item_id, 'sale_deduction', -p_quantity, v_current_qty, v_new_qty, v_sale_code, p_created_by
  );

  -- 7. Create a debt for this sale if it is a Debt Credit order.
  --    Cash orders never create a new debt for this sale — old debts were
  --    already reduced above; the new sale is fully settled as cash.
  if p_payment_type = 'debt' then
    insert into public.debts (
      sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at
    ) values (
      v_sale_id, p_customer_id, v_total_amount, 0, v_total_amount, 'pending', v_now
    ) returning id into v_debt_id;
  end if;

  return jsonb_build_object(
    'id', v_sale_id,
    'sale_code', v_sale_code,
    'customer_id', p_customer_id,
    'cube_type', p_cube_type,
    'quantity', p_quantity,
    'price_per_cube', v_final_price,
    'total_amount', v_total_amount,
    'payment_type', p_payment_type,
    'sale_date', v_now,
    'debt_id', v_debt_id,
    'applied_to_old_debt', v_applied_to_old_debt
  );
end;
$$ language plpgsql security definer;

-- Atomic Multi-Item Order Placement Transaction (SalesTab.md: a "+Add Row"
-- order with two cube types saves as ONE bill, not one sale per row).
-- Same cash-to-old-debt FIFO offset and admin-price-override rules as
-- place_order_transaction (kept in place, unused after this — harmless as
-- an additive no-op since nothing else calls it), just generalized across a
-- jsonb array of {cube_type, quantity, price_per_cube} items instead of a
-- single item. Since there are only ever two cube types, inventory rows are
-- locked in the fixed order manufactured-then-resell (rather than a generic
-- loop) to avoid deadlocking against concurrent orders/edits touching both.
create or replace function public.place_multi_item_order_transaction(
  p_customer_id bigint,
  p_items jsonb,
  p_payment_type text,
  p_created_by text
) returns jsonb as $$
declare
  v_item record;
  v_mfc_id bigint;
  v_mfc_qty integer;
  v_mfc_price numeric(10, 2);
  v_mfc_needed integer := 0;
  v_rsc_id bigint;
  v_rsc_qty integer;
  v_rsc_price numeric(10, 2);
  v_rsc_needed integer := 0;

  v_customer_mfc_price numeric(10, 2);
  v_customer_rsc_price numeric(10, 2);
  v_default_mfc_price numeric(10, 2);
  v_default_rsc_price numeric(10, 2);

  v_sale_code text;
  v_sale_id bigint;
  v_total_amount numeric(10, 2) := 0;
  v_now timestamp with time zone := timezone('utc'::text, now());
  v_resolved_price numeric(10, 2);
  v_item_subtotal numeric(10, 2);
  v_resolved_items jsonb := '[]'::jsonb;

  v_single_cube_type text;
  v_single_price numeric(10, 2);
  v_price_consistent boolean := true;

  v_debt_id bigint := null;
  v_cash_remaining numeric(10, 2);
  v_applied_to_old_debt numeric(10, 2) := 0;
  v_old_debt record;
  v_apply_amt numeric(10, 2);
  v_old_new_remaining numeric(10, 2);
  v_old_new_status text;
begin
  if p_customer_id is null then raise exception 'Customer is required'; end if;
  if p_payment_type not in ('cash', 'debt') then raise exception 'Invalid payment type'; end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then raise exception 'At least one order item is required'; end if;

  -- 1. Validate items and tally the requested quantity per cube type
  for v_item in select * from jsonb_to_recordset(p_items) as x(cube_type text, quantity integer, price_per_cube numeric) loop
    if v_item.cube_type not in ('manufactured', 'resell') then raise exception 'Invalid cube type selected'; end if;
    if v_item.quantity is null or v_item.quantity <= 0 then raise exception 'All row quantities must be positive integers'; end if;

    if v_item.cube_type = 'manufactured' then
      v_mfc_needed := v_mfc_needed + v_item.quantity;
    else
      v_rsc_needed := v_rsc_needed + v_item.quantity;
    end if;
  end loop;

  -- 2. Lock the inventory row(s) actually needed, in fixed alphabetical order
  if v_mfc_needed > 0 then
    select id, quantity, price_per_cube into v_mfc_id, v_mfc_qty, v_mfc_price
    from public.inventory where type = 'manufactured' for update;
    if not found then raise exception 'Inventory item for manufactured not found'; end if;
    if v_mfc_qty < v_mfc_needed then raise exception 'Insufficient Production stock. Available: %', v_mfc_qty; end if;
    if v_mfc_price is null or v_mfc_price <= 0 then raise exception 'Price per cube must be set before placing a sale'; end if;
  end if;

  if v_rsc_needed > 0 then
    select id, quantity, price_per_cube into v_rsc_id, v_rsc_qty, v_rsc_price
    from public.inventory where type = 'resell' for update;
    if not found then raise exception 'Inventory item for resell not found'; end if;
    if v_rsc_qty < v_rsc_needed then raise exception 'Insufficient Resell stock. Available: %', v_rsc_qty; end if;
    if v_rsc_price is null or v_rsc_price <= 0 then raise exception 'Price per cube must be set before placing a sale'; end if;
  end if;

  -- 3. Deduct the summed quantity per type
  if v_mfc_needed > 0 then
    update public.inventory set quantity = v_mfc_qty - v_mfc_needed, updated_at = v_now where id = v_mfc_id;
  end if;
  if v_rsc_needed > 0 then
    update public.inventory set quantity = v_rsc_qty - v_rsc_needed, updated_at = v_now where id = v_rsc_id;
  end if;

  -- 4. One sale_code for the whole order
  v_sale_code := public.get_next_code('sale', 'S');

  -- 4b. This customer's per-cube custom rates, if any — the non-admin
  --     default is their custom price when set, otherwise the live
  --     inventory price (customer_cube_prices is looked up server-side so
  --     it can't be spoofed by a client-supplied price_per_cube).
  select price_per_cube into v_customer_mfc_price
  from public.customer_cube_prices
  where customer_id = p_customer_id and cube_type = 'manufactured';

  select price_per_cube into v_customer_rsc_price
  from public.customer_cube_prices
  where customer_id = p_customer_id and cube_type = 'resell';

  v_default_mfc_price := coalesce(v_customer_mfc_price, v_mfc_price);
  v_default_rsc_price := coalesce(v_customer_rsc_price, v_rsc_price);

  -- 5. Resolve each item's final price (admin override honored per item;
  --    everyone else gets this customer's custom rate if set, otherwise the
  --    live inventory price for that item's cube type) and accumulate the total.
  for v_item in select * from jsonb_to_recordset(p_items) as x(cube_type text, quantity integer, price_per_cube numeric) loop
    if public.is_admin() and v_item.price_per_cube is not null and v_item.price_per_cube > 0 then
      v_resolved_price := v_item.price_per_cube;
    else
      v_resolved_price := case when v_item.cube_type = 'manufactured' then v_default_mfc_price else v_default_rsc_price end;
    end if;

    v_item_subtotal := v_resolved_price * v_item.quantity;
    v_total_amount := v_total_amount + v_item_subtotal;

    v_resolved_items := v_resolved_items || jsonb_build_object(
      'cube_type', v_item.cube_type,
      'quantity', v_item.quantity,
      'price_per_cube', v_resolved_price,
      'subtotal', v_item_subtotal
    );

    if v_single_cube_type is null then
      v_single_cube_type := v_item.cube_type;
      v_single_price := v_resolved_price;
    elsif v_single_cube_type <> v_item.cube_type or v_single_price <> v_resolved_price then
      v_price_consistent := false;
    end if;
  end loop;

  -- 6. Cash-to-old-debt FIFO offset (cash orders only) — identical logic to
  --    place_order_transaction, applied against the combined order total.
  if p_payment_type = 'cash' then
    v_cash_remaining := v_total_amount;

    for v_old_debt in
      select id, remaining_amount
      from public.debts
      where customer_id = p_customer_id
        and status in ('pending', 'partial')
      order by created_at asc
      for update
    loop
      exit when v_cash_remaining <= 0;

      v_apply_amt := least(v_cash_remaining, v_old_debt.remaining_amount);
      v_old_new_remaining := v_old_debt.remaining_amount - v_apply_amt;
      v_old_new_status := case when v_old_new_remaining <= 0 then 'settled' else 'partial' end;

      update public.debts
      set paid_amount     = paid_amount + v_apply_amt,
          remaining_amount = v_old_new_remaining,
          status          = v_old_new_status,
          created_at      = case when v_old_new_remaining > 0 then v_now else created_at end
      where id = v_old_debt.id;

      insert into public.debt_settlements (debt_id, customer_id, amount_paid, settlement_date, created_by)
      values (v_old_debt.id, p_customer_id, v_apply_amt, v_now,
              p_created_by || ' (auto-applied from sale ' || v_sale_code || ')');

      v_applied_to_old_debt := v_applied_to_old_debt + v_apply_amt;
      v_cash_remaining := v_cash_remaining - v_apply_amt;
    end loop;
  end if;

  -- 7. Insert the one sales header row. Legacy cube_type/price_per_cube are
  --    populated only when the whole order is a single (type, price) pair.
  insert into public.sales (
    sale_code, customer_id, cube_type, quantity, price_per_cube, total_amount, payment_type, sale_date, created_by
  ) values (
    v_sale_code, p_customer_id,
    case when v_price_consistent then v_single_cube_type else null end,
    v_mfc_needed + v_rsc_needed,
    case when v_price_consistent then v_single_price else null end,
    v_total_amount, p_payment_type, v_now, p_created_by
  ) returning id into v_sale_id;

  -- 8. Insert one sale_items row per input item
  for v_item in select * from jsonb_to_recordset(v_resolved_items) as y(cube_type text, quantity integer, price_per_cube numeric, subtotal numeric) loop
    insert into public.sale_items (sale_id, cube_type, quantity, price_per_cube, subtotal)
    values (v_sale_id, v_item.cube_type, v_item.quantity, v_item.price_per_cube, v_item.subtotal);
  end loop;

  -- 9. Inventory audit log, one row per type actually deducted
  if v_mfc_needed > 0 then
    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_mfc_id, 'sale_deduction', -v_mfc_needed, v_mfc_qty, v_mfc_qty - v_mfc_needed, v_sale_code, p_created_by);
  end if;
  if v_rsc_needed > 0 then
    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_rsc_id, 'sale_deduction', -v_rsc_needed, v_rsc_qty, v_rsc_qty - v_rsc_needed, v_sale_code, p_created_by);
  end if;

  -- 10. Create a debt for this sale if it is a Debt Credit order (unchanged
  --     pattern — one debt row keyed by sale_id/total_amount, agnostic to
  --     item count).
  if p_payment_type = 'debt' then
    insert into public.debts (
      sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at
    ) values (
      v_sale_id, p_customer_id, v_total_amount, 0, v_total_amount, 'pending', v_now
    ) returning id into v_debt_id;
  end if;

  return jsonb_build_object(
    'id', v_sale_id,
    'sale_code', v_sale_code,
    'customer_id', p_customer_id,
    'total_amount', v_total_amount,
    'payment_type', p_payment_type,
    'sale_date', v_now,
    'debt_id', v_debt_id,
    'applied_to_old_debt', v_applied_to_old_debt
  );
end;
$$ language plpgsql security definer;

-- Atomic Debt Settlement Transaction
-- Locks the debt row so two concurrent/duplicate settlements can never both
-- apply against the same "remaining_amount" snapshot (fixes lost-payment
-- race), and updates the debt + inserts the audit row in one transaction so
-- a failure can never leave the debt updated without a matching settlement
-- record (fixes double-apply-on-retry).
create or replace function public.settle_debt_transaction(
  p_debt_id bigint,
  p_amount_paid numeric,
  p_created_by text,
  p_payment_method text default 'cash',
  p_notes text default null
) returns jsonb as $$
declare
  v_total numeric(10, 2);
  v_paid numeric(10, 2);
  v_remaining numeric(10, 2);
  v_customer_id bigint;
  v_sale_id bigint;
  v_new_paid numeric(10, 2);
  v_new_remaining numeric(10, 2);
  v_new_status text;
  v_settlement_code text;
  v_settlement_id bigint;
  v_now timestamp with time zone := timezone('utc'::text, now());
begin
  if p_amount_paid is null or p_amount_paid <= 0 then
    raise exception 'Settlement amount must be a positive number';
  end if;

  select total_amount, paid_amount, remaining_amount, customer_id, sale_id
    into v_total, v_paid, v_remaining, v_customer_id, v_sale_id
  from public.debts
  where id = p_debt_id
  for update;

  if not found then
    raise exception 'Debt record not found';
  end if;

  if p_amount_paid > v_remaining then
    raise exception 'Payment exceeds outstanding debt. Max payable: LKR %', v_remaining;
  end if;

  v_new_paid := v_paid + p_amount_paid;
  v_new_remaining := v_total - v_new_paid;
  v_new_status := case when v_new_remaining <= 0 then 'settled' else 'partial' end;

  update public.debts
  set paid_amount = v_new_paid,
      remaining_amount = v_new_remaining,
      status = v_new_status
  where id = p_debt_id;

  v_settlement_code := public.get_next_code('settlement', 'D');

  insert into public.debt_settlements (
    debt_id, customer_id, amount_paid, payment_method, notes, settlement_date, created_by
  ) values (
    p_debt_id, v_customer_id, p_amount_paid, coalesce(p_payment_method, 'cash'), p_notes, v_now, p_created_by
  ) returning id into v_settlement_id;

  return jsonb_build_object(
    'id', v_settlement_id,
    'settlement_code', v_settlement_code,
    'debt_id', p_debt_id,
    'customer_id', v_customer_id,
    'sale_id', v_sale_id,
    'amount_paid', p_amount_paid,
    'payment_method', coalesce(p_payment_method, 'cash'),
    'notes', p_notes,
    'remaining_amount', v_new_remaining,
    'status', v_new_status,
    'settlement_date', v_now
  );
end;
$$ language plpgsql security definer;

-- Atomic Sale Edit Transaction (SalesTab.md "Edit bill button")
-- Lets an existing sale's cube type / quantity / rate / payment terms be
-- corrected after the fact, while keeping inventory and the debts ledger
-- consistent:
--   - Inventory: the sale's original quantity is restored to its original
--     cube type's stock, then the new quantity is deducted from the new
--     cube type's stock (same row if the type didn't change). Both affected
--     inventory rows are locked in a fixed (alphabetical) order so two
--     concurrent edits/orders can never deadlock against each other.
--   - Debts: cash->cash / debt->debt just re-prices the linked debt (if
--     any). debt->cash deletes the debt, but only if nothing has been paid
--     against it yet (paid_amount = 0) — refuses otherwise, since silently
--     dropping a debt that already has settlement history would destroy
--     that payment record. cash->debt creates a fresh pending debt for the
--     new total. Note: unlike place_order_transaction, this does NOT replay
--     the cash-to-old-debt FIFO offset — that offset already happened (or
--     didn't) at the time the sale was originally placed.
create or replace function public.edit_sale_transaction(
  p_sale_id bigint,
  p_cube_type text,
  p_quantity integer,
  p_price_per_cube numeric,
  p_payment_type text,
  p_edited_by text
) returns jsonb as $$
declare
  v_old_cube_type text;
  v_old_quantity integer;
  v_old_payment_type text;
  v_customer_id bigint;
  v_sale_code text;

  v_type_a text;
  v_type_b text;
  v_item_a_id bigint;
  v_item_a_qty integer;
  v_item_b_id bigint;
  v_item_b_qty integer;

  v_old_item_id bigint;
  v_old_item_qty integer;
  v_new_item_id bigint;
  v_new_item_qty integer;

  v_old_item_final_qty integer;
  v_new_item_final_qty integer;

  v_inventory_price numeric(10, 2);
  v_final_price numeric(10, 2);
  v_new_total numeric(10, 2);
  v_now timestamp with time zone := timezone('utc'::text, now());

  v_debt_id bigint;
  v_debt_paid numeric(10, 2);
  v_new_remaining numeric(10, 2);
  v_new_status text;
begin
  if p_quantity is null or p_quantity <= 0 then raise exception 'Quantity must be a positive integer'; end if;
  if p_cube_type not in ('manufactured', 'resell') then raise exception 'Invalid cube type selected'; end if;
  if p_payment_type not in ('cash', 'debt') then raise exception 'Invalid payment type'; end if;

  -- 1. Lock and read the existing sale
  select cube_type, quantity, payment_type, customer_id, sale_code
    into v_old_cube_type, v_old_quantity, v_old_payment_type, v_customer_id, v_sale_code
  from public.sales
  where id = p_sale_id
  for update;

  if not found then raise exception 'Sale record not found'; end if;

  -- 2. Lock the affected inventory row(s) in a fixed order to avoid deadlocks
  --    against concurrent edits/orders touching the same two cube types.
  if v_old_cube_type = p_cube_type then
    select id, quantity into v_old_item_id, v_old_item_qty
    from public.inventory where type = v_old_cube_type for update;
    if not found then raise exception 'Inventory item for % not found', v_old_cube_type; end if;
    v_new_item_id := v_old_item_id;
    v_new_item_qty := v_old_item_qty;
  else
    if v_old_cube_type < p_cube_type then
      v_type_a := v_old_cube_type; v_type_b := p_cube_type;
    else
      v_type_a := p_cube_type; v_type_b := v_old_cube_type;
    end if;

    select id, quantity into v_item_a_id, v_item_a_qty
    from public.inventory where type = v_type_a for update;
    if not found then raise exception 'Inventory item for % not found', v_type_a; end if;

    select id, quantity into v_item_b_id, v_item_b_qty
    from public.inventory where type = v_type_b for update;
    if not found then raise exception 'Inventory item for % not found', v_type_b; end if;

    if v_type_a = v_old_cube_type then
      v_old_item_id := v_item_a_id; v_old_item_qty := v_item_a_qty;
      v_new_item_id := v_item_b_id; v_new_item_qty := v_item_b_qty;
    else
      v_old_item_id := v_item_b_id; v_old_item_qty := v_item_b_qty;
      v_new_item_id := v_item_a_id; v_new_item_qty := v_item_a_qty;
    end if;
  end if;

  -- 3. Restore the old quantity, then deduct the new quantity
  if v_old_item_id = v_new_item_id then
    v_old_item_final_qty := v_old_item_qty + v_old_quantity - p_quantity;
    if v_old_item_final_qty < 0 then
      raise exception 'Insufficient stock. Available: %', v_old_item_qty + v_old_quantity;
    end if;

    update public.inventory
    set quantity = v_old_item_final_qty, updated_at = v_now
    where id = v_old_item_id;

    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_old_item_id, 'adjustment', v_old_item_final_qty - v_old_item_qty, v_old_item_qty, v_old_item_final_qty, v_sale_code || ' (edit)', p_edited_by);
  else
    v_old_item_final_qty := v_old_item_qty + v_old_quantity;
    v_new_item_final_qty := v_new_item_qty - p_quantity;
    if v_new_item_final_qty < 0 then
      raise exception 'Insufficient stock. Available: %', v_new_item_qty;
    end if;

    update public.inventory
    set quantity = v_old_item_final_qty, updated_at = v_now
    where id = v_old_item_id;

    update public.inventory
    set quantity = v_new_item_final_qty, updated_at = v_now
    where id = v_new_item_id;

    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_old_item_id, 'adjustment', v_old_quantity, v_old_item_qty, v_old_item_final_qty, v_sale_code || ' (edit restore)', p_edited_by);

    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_new_item_id, 'adjustment', -p_quantity, v_new_item_qty, v_new_item_final_qty, v_sale_code || ' (edit deduct)', p_edited_by);
  end if;

  -- 4. Resolve price the same way place_order_transaction does: admins may
  --    override, everyone else always gets the current inventory price.
  select price_per_cube into v_inventory_price from public.inventory where id = v_new_item_id;

  if public.is_admin() and p_price_per_cube is not null and p_price_per_cube > 0 then
    v_final_price := p_price_per_cube;
  else
    v_final_price := v_inventory_price;
  end if;

  if v_final_price is null or v_final_price <= 0 then
    raise exception 'Price per cube must be a valid positive number';
  end if;

  v_new_total := v_final_price * p_quantity;

  -- 5. Update the sale record
  update public.sales
  set cube_type = p_cube_type,
      quantity = p_quantity,
      price_per_cube = v_final_price,
      total_amount = v_new_total,
      payment_type = p_payment_type,
      bill_pdf_url = null
  where id = p_sale_id;

  -- 6. Reconcile the linked debt (if any) against the new payment terms/total
  select id, paid_amount into v_debt_id, v_debt_paid
  from public.debts
  where sale_id = p_sale_id
  for update;

  if v_old_payment_type = 'debt' and p_payment_type = 'debt' then
    -- Still a debt: re-price it, keeping whatever has already been paid.
    v_new_remaining := v_new_total - coalesce(v_debt_paid, 0);
    if v_new_remaining < 0 then
      raise exception 'New total (LKR %) is less than the LKR % already paid against this debt', v_new_total, v_debt_paid;
    end if;
    v_new_status := case when v_new_remaining <= 0 then 'settled' else (case when v_debt_paid > 0 then 'partial' else 'pending' end) end;

    update public.debts
    set total_amount = v_new_total,
        remaining_amount = v_new_remaining,
        status = v_new_status
    where id = v_debt_id;

  elsif v_old_payment_type = 'debt' and p_payment_type = 'cash' then
    -- Converting to cash: only safe to drop the debt if nothing has been
    -- collected against it yet.
    if v_debt_id is not null and coalesce(v_debt_paid, 0) > 0 then
      raise exception 'Cannot convert to cash: LKR % has already been settled against this sale''s debt', v_debt_paid;
    end if;
    delete from public.debts where id = v_debt_id;

  elsif v_old_payment_type = 'cash' and p_payment_type = 'debt' then
    -- Converting to debt: open a fresh pending debt for the new total.
    insert into public.debts (sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at)
    values (p_sale_id, v_customer_id, v_new_total, 0, v_new_total, 'pending', v_now)
    returning id into v_debt_id;
  end if;

  return jsonb_build_object(
    'id', p_sale_id,
    'sale_code', v_sale_code,
    'customer_id', v_customer_id,
    'cube_type', p_cube_type,
    'quantity', p_quantity,
    'price_per_cube', v_final_price,
    'total_amount', v_new_total,
    'payment_type', p_payment_type,
    'debt_id', v_debt_id
  );
end;
$$ language plpgsql security definer;

-- Atomic Inventory Update Price
create or replace function public.update_inventory_price(p_id bigint, p_price numeric)
returns void as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update inventory prices';
  end if;
  
  if p_price <= 0 then
    raise exception 'Price must be a positive value';
  end if;

  update public.inventory
  set price_per_cube = p_price,
      updated_at = timezone('utc'::text, now())
  where id = p_id;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 5. Tightened RLS Policies Definition
-- ==========================================

-- Profiles policies
create policy "Allow read profiles for authenticated" on public.profiles
  for select to authenticated using (true);

create policy "Allow update profiles for admins" on public.profiles
  for update to authenticated using (public.is_admin());

-- Inventory policies
create policy "Allow read inventory for authenticated" on public.inventory
  for select to authenticated using (true);

create policy "Allow admin write inventory" on public.inventory
  for all to authenticated using (public.is_admin());

-- Settings policies (authenticated read only, admin write)
create policy "Allow read settings for authenticated" on public.settings
  for select to authenticated using (true);

create policy "Allow write settings for admins" on public.settings
  for all to authenticated using (public.is_admin());

-- Code Counters policies
create policy "Allow read code_counters for authenticated" on public.code_counters
  for select to authenticated using (true);

create policy "Allow update code_counters for authenticated" on public.code_counters
  for all to authenticated using (true);

-- Customers policies
create policy "Allow read customers for authenticated" on public.customers
  for select to authenticated using (true);

create policy "Allow insert customers for authenticated" on public.customers
  for insert to authenticated with check (true);

create policy "Allow update customers for admins" on public.customers
  for update to authenticated using (public.is_admin());

create policy "Allow delete customers for admins" on public.customers
  for delete to authenticated using (public.is_admin());

-- Vehicles policies
create policy "Allow read vehicles for authenticated" on public.vehicles
  for select to authenticated using (true);

create policy "Allow insert vehicles for authenticated" on public.vehicles
  for insert to authenticated with check (true);

create policy "Allow update vehicles for admins" on public.vehicles
  for update to authenticated using (public.is_admin());

create policy "Allow delete vehicles for admins" on public.vehicles
  for delete to authenticated using (public.is_admin());

-- Vehicle Trips policies
create policy "Allow read vehicle_trips for authenticated" on public.vehicle_trips
  for select to authenticated using (true);

create policy "Allow insert vehicle_trips for authenticated" on public.vehicle_trips
  for insert to authenticated with check (true);

create policy "Allow delete vehicle_trips for admins" on public.vehicle_trips
  for delete to authenticated using (public.is_admin());

-- Employees policies
create policy "Allow read employees for authenticated" on public.employees
  for select to authenticated using (true);

create policy "Allow insert employees for authenticated" on public.employees
  for insert to authenticated with check (true);

create policy "Allow update employees for admins" on public.employees
  for update to authenticated using (public.is_admin());

create policy "Allow delete employees for admins" on public.employees
  for delete to authenticated using (public.is_admin());

-- Employee Attendance policies
create policy "Allow read employee_attendance for authenticated" on public.employee_attendance
  for select to authenticated using (true);

create policy "Allow insert employee_attendance for authenticated" on public.employee_attendance
  for insert to authenticated with check (true);

create policy "Allow update employee_attendance for authenticated" on public.employee_attendance
  for update to authenticated using (true);

create policy "Allow delete employee_attendance for admins" on public.employee_attendance
  for delete to authenticated using (public.is_admin());

-- Transport Trips policies
create policy "Allow read transport_trips for authenticated" on public.transport_trips
  for select to authenticated using (true);

create policy "Allow insert transport_trips for authenticated" on public.transport_trips
  for insert to authenticated with check (true);

create policy "Allow update transport_trips for authenticated" on public.transport_trips
  for update to authenticated using (true);

create policy "Allow delete transport_trips for admins" on public.transport_trips
  for delete to authenticated using (public.is_admin());

-- Sales policies
create policy "Allow read sales for authenticated" on public.sales
  for select to authenticated using (true);

create policy "Allow insert sales for authenticated" on public.sales
  for insert to authenticated with check (true);

create policy "Allow update sales for admins" on public.sales
  for update to authenticated using (public.is_admin());

create policy "Allow delete sales for admins" on public.sales
  for delete to authenticated using (public.is_admin());

-- Sale items policies
create policy "Allow read sale_items for authenticated" on public.sale_items
  for select to authenticated using (true);

create policy "Allow insert sale_items for authenticated" on public.sale_items
  for insert to authenticated with check (true);

create policy "Allow update sale_items for admins" on public.sale_items
  for update to authenticated using (public.is_admin());

create policy "Allow delete sale_items for admins" on public.sale_items
  for delete to authenticated using (public.is_admin());

-- Debts policies
create policy "Allow read debts for authenticated" on public.debts
  for select to authenticated using (true);

create policy "Allow insert debts for authenticated" on public.debts
  for insert to authenticated with check (true);

create policy "Allow update debts for authenticated" on public.debts
  for update to authenticated using (true);

create policy "Allow delete debts for admins" on public.debts
  for delete to authenticated using (public.is_admin());

-- Debt Settlements policies
create policy "Allow read settlements for authenticated" on public.debt_settlements
  for select to authenticated using (true);

create policy "Allow insert settlements for authenticated" on public.debt_settlements
  for insert to authenticated with check (true);

create policy "Allow delete settlements for admins" on public.debt_settlements
  for delete to authenticated using (public.is_admin());

create policy "Allow read customer_cube_prices for authenticated" on public.customer_cube_prices
  for select to authenticated using (true);

create policy "Allow insert customer_cube_prices for admins" on public.customer_cube_prices
  for insert to authenticated with check (public.is_admin());

create policy "Allow update customer_cube_prices for admins" on public.customer_cube_prices
  for update to authenticated using (public.is_admin());

create policy "Allow delete customer_cube_prices for admins" on public.customer_cube_prices
  for delete to authenticated using (public.is_admin());

-- ==========================================
-- 6. Trigger to Create Profile on User Signup
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce(new.raw_user_meta_data->>'role', 'user')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Expenses: dynamic categories/expense-items + Cash Book grid (ledger rows x
-- per-item amounts). See ExpensesTab.md for the full UI/behavior spec.
create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  category_code text not null unique,
  name text not null unique,
  position integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.expense_items (
  id bigint generated by default as identity primary key,
  expense_code text not null unique,
  name text not null,
  category_id bigint not null references public.expense_categories(id) on delete cascade,
  position integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (category_id, name)
);

create table if not exists public.expense_ledger_rows (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  description text not null default '',
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.expense_amounts (
  id bigint generated by default as identity primary key,
  ledger_row_id bigint not null references public.expense_ledger_rows(id) on delete cascade,
  expense_item_id bigint not null references public.expense_items(id) on delete cascade,
  amount numeric(12, 2) not null default 0 check (amount >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (ledger_row_id, expense_item_id)
);

create index if not exists idx_expense_items_category on public.expense_items(category_id);
create index if not exists idx_expense_amounts_ledger_row on public.expense_amounts(ledger_row_id);
create index if not exists idx_expense_amounts_item on public.expense_amounts(expense_item_id);
create index if not exists idx_expense_ledger_rows_date on public.expense_ledger_rows(entry_date);

alter table public.expense_categories enable row level security;
alter table public.expense_items enable row level security;
alter table public.expense_ledger_rows enable row level security;
alter table public.expense_amounts enable row level security;

create policy "Allow read expense_categories" on public.expense_categories for select to authenticated using (true);
create policy "Allow write expense_categories" on public.expense_categories for all to authenticated using (true);

create policy "Allow read expense_items" on public.expense_items for select to authenticated using (true);
create policy "Allow write expense_items" on public.expense_items for all to authenticated using (true);

create policy "Allow read expense_ledger_rows" on public.expense_ledger_rows for select to authenticated using (true);
create policy "Allow write expense_ledger_rows" on public.expense_ledger_rows for all to authenticated using (true);

create policy "Allow read expense_amounts" on public.expense_amounts for select to authenticated using (true);
create policy "Allow write expense_amounts" on public.expense_amounts for all to authenticated using (true);

-- ==========================================
-- 8. Supabase Storage Bucket & Private Bills Storage Setup
-- ==========================================

-- Create private storage bucket 'bills' (public = false)
insert into storage.buckets (id, name, public)
values ('bills', 'bills', false)
on conflict (id) do update set public = false;

-- Storage policies for private bucket 'bills' (Authenticated only)
drop policy if exists "Public Access to Bills" on storage.objects;
drop policy if exists "Authenticated Access to Bills" on storage.objects;
create policy "Authenticated Access to Bills" on storage.objects
  for select to authenticated using (bucket_id = 'bills');

drop policy if exists "Allow Insert Bills for Authenticated & Public" on storage.objects;
create policy "Allow Insert Bills for Authenticated" on storage.objects
  for insert to authenticated with check (bucket_id = 'bills');

drop policy if exists "Allow Delete Bills for Authenticated" on storage.objects;
create policy "Allow Delete Bills for Authenticated" on storage.objects
  for delete to authenticated using (bucket_id = 'bills');

-- Function to purge PDF bills created > 24 hours ago
create or replace function public.purge_expired_pdf_bills()
returns void as $$
begin
  -- Delete storage objects in bucket 'bills' older than 24 hours
  delete from storage.objects
  where bucket_id = 'bills'
    and created_at < (now() - interval '24 hours');
    
  -- Reset bill_pdf_url on sales older than 24 hours
  update public.sales
  set bill_pdf_url = null
  where sale_date < (now() - interval '24 hours')
    and bill_pdf_url is not null;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 9. Daily Manager Reports Table Setup
-- ==========================================

create table if not exists public.daily_manager_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  free_issue integer default 0,
  damaged_cubes integer default 0,
  other_receipts numeric(10, 2) default 0,
  other_details text default '',

  verified_by text default '',
  verified_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.daily_manager_reports enable row level security;
create policy "Allow read daily_manager_reports" on public.daily_manager_reports for select to authenticated using (true);
create policy "Allow write daily_manager_reports" on public.daily_manager_reports for all to authenticated using (true);

-- ==========================================
-- 10. Cash & Bank Management: dedicated history ledgers
-- ==========================================
-- Replaces the JSONB-in-one-row approach (daily_manager_reports.cheque_entries
-- / withdrawals) with permanent, queryable history tables. See
-- Cash&BankManagement.md for the full spec.

create table if not exists public.cash_receives (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  receive_type text not null check (receive_type in ('head_office', 'other')),
  received_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.bank_deposits (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  cash_method text not null check (cash_method in ('sales', 'other', 'cheques')),
  bank_name text,
  deposited_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.cheque_records (
  id bigint generated by default as identity primary key,
  cheque_no text not null,
  bank_name text not null,
  amount numeric(12, 2) not null check (amount > 0),
  payer_name text not null,
  status text not null default 'pending' check (status in ('pending', 'deposited')),
  received_at timestamp with time zone not null default timezone('utc'::text, now()),
  deposited_at timestamp with time zone,
  deposit_id bigint references public.bank_deposits(id) on delete set null,
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.bank_withdrawals (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  bank_name text not null,
  purpose text not null,
  withdrawn_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_cash_receives_received_at on public.cash_receives(received_at);
create index if not exists idx_bank_deposits_deposited_at on public.bank_deposits(deposited_at);
create index if not exists idx_bank_deposits_bank_name on public.bank_deposits(bank_name);
create index if not exists idx_cheque_records_status on public.cheque_records(status);
create index if not exists idx_cheque_records_received_at on public.cheque_records(received_at);
create index if not exists idx_bank_withdrawals_withdrawn_at on public.bank_withdrawals(withdrawn_at);
create index if not exists idx_bank_withdrawals_bank_name on public.bank_withdrawals(bank_name);

alter table public.cash_receives enable row level security;
alter table public.bank_deposits enable row level security;
alter table public.cheque_records enable row level security;
alter table public.bank_withdrawals enable row level security;

create policy "Allow read cash_receives" on public.cash_receives for select to authenticated using (true);
create policy "Allow write cash_receives" on public.cash_receives for all to authenticated using (true);

create policy "Allow read bank_deposits" on public.bank_deposits for select to authenticated using (true);
create policy "Allow write bank_deposits" on public.bank_deposits for all to authenticated using (true);

create policy "Allow read cheque_records" on public.cheque_records for select to authenticated using (true);
create policy "Allow write cheque_records" on public.cheque_records for all to authenticated using (true);

create policy "Allow read bank_withdrawals" on public.bank_withdrawals for select to authenticated using (true);
create policy "Allow write bank_withdrawals" on public.bank_withdrawals for all to authenticated using (true);

-- Notes and Messages Tab: a simple notes ledger where any authenticated
-- user can add timestamped notes visible to all staff.

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  note_text text not null,
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_notes_created_at on public.notes(created_at desc);

alter table public.notes enable row level security;

create policy "Allow read notes for authenticated" on public.notes
  for select to authenticated using (true);
create policy "Allow insert notes for authenticated" on public.notes
  for insert to authenticated with check (true);
create policy "Allow delete notes for admins" on public.notes
  for delete to authenticated using (public.is_admin());

-- Recent Actions: system-wide audit trail. Insert is open to any
-- authenticated user (everyone's actions get logged); reading/pruning the
-- log is admin-only.

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_label text,
  description text not null,
  performed_by text not null,
  performed_by_role text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_activity_log_created_at on public.activity_log(created_at desc);

alter table public.activity_log enable row level security;

create policy "Allow insert activity_log for authenticated" on public.activity_log
  for insert to authenticated with check (true);
create policy "Allow select activity_log for admins" on public.activity_log
  for select to authenticated using (public.is_admin());
create policy "Allow delete activity_log for admins" on public.activity_log
  for delete to authenticated using (public.is_admin());

-- Trash / recoverable deletes: a generic snapshot table plus a small set of
-- security-definer functions replace direct `.delete()` calls across the
-- app. See supabase/migrations/20260823020500_trash_recovery.sql for the
-- full design rationale.

create table if not exists public.trash (
  id bigint generated by default as identity primary key,
  entity_table text not null,
  entity_id text not null,
  entity_label text,
  snapshot jsonb not null,
  deleted_by text not null,
  deleted_at timestamptz not null default timezone('utc', now()),
  purge_at timestamptz not null default timezone('utc', now()) + interval '7 days'
);

create index if not exists idx_trash_purge_at on public.trash(purge_at);

alter table public.trash enable row level security;

create policy "Allow select trash for admins" on public.trash
  for select to authenticated using (public.is_admin());

create or replace function public.soft_delete_row(
  p_table text,
  p_id bigint,
  p_deleted_by text,
  p_deleted_by_role text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_children jsonb := '[]'::jsonb;
  v_label text;
begin
  if p_table not in (
    'customers', 'sales', 'debts', 'notes', 'employees', 'vehicles',
    'bank_deposits', 'cheque_records', 'bank_withdrawals', 'cash_receives',
    'customer_cube_prices', 'employee_attendance', 'vehicle_trips',
    'transport_trips', 'expense_ledger_rows'
  ) then
    raise exception 'Table % is not allowed for soft delete', p_table;
  end if;

  execute format('select to_jsonb(t) from public.%I t where id = $1', p_table)
    into v_row using p_id;

  if v_row is null then
    raise exception 'Row not found in %', p_table;
  end if;

  if p_table = 'sales' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'sale_items',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.sale_items t where t.sale_id = p_id), '[]'::jsonb)
    ));
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'debts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.debts t where t.sale_id = p_id), '[]'::jsonb),
      'children', coalesce((
        select jsonb_agg(jsonb_build_object(
          'table', 'debt_settlements',
          'rows', coalesce((select jsonb_agg(to_jsonb(s)) from public.debt_settlements s where s.debt_id = d.id), '[]'::jsonb)
        ))
        from public.debts d where d.sale_id = p_id
      ), '[]'::jsonb)
    ));
  elsif p_table = 'customers' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'debts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.debts t where t.customer_id = p_id), '[]'::jsonb),
      'children', coalesce((
        select jsonb_agg(jsonb_build_object(
          'table', 'debt_settlements',
          'rows', coalesce((select jsonb_agg(to_jsonb(s)) from public.debt_settlements s where s.debt_id = d.id), '[]'::jsonb)
        ))
        from public.debts d where d.customer_id = p_id
      ), '[]'::jsonb)
    ));
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'transport_trips',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.transport_trips t where t.customer_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'vehicles' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'vehicle_trips',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.vehicle_trips t where t.vehicle_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'employees' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'employee_attendance',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.employee_attendance t where t.employee_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'expense_ledger_rows' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'expense_amounts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.expense_amounts t where t.ledger_row_id = p_id), '[]'::jsonb)
    ));
  end if;

  v_label := coalesce(
    v_row->>'customer_code', v_row->>'sale_code', v_row->>'employee_code',
    v_row->>'vehicle_no', v_row->>'expense_code', v_row->>'category_code',
    v_row->>'name', v_row->>'note_text', v_row->>'id'
  );

  insert into public.trash (entity_table, entity_id, entity_label, snapshot, deleted_by)
  values (p_table, p_id::text, v_label, jsonb_build_object('row', v_row, 'children', v_children), p_deleted_by);

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by, performed_by_role)
  values ('delete', p_table, p_id::text, v_label, format('Deleted %s %s', p_table, coalesce(v_label, p_id::text)), p_deleted_by, p_deleted_by_role);

  execute format('delete from public.%I where id = $1', p_table) using p_id;
end;
$$;

grant execute on function public.soft_delete_row(text, bigint, text, text) to authenticated;

create or replace function public.restore_trash_item(p_trash_id bigint, p_performed_by text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trash public.trash%rowtype;
  v_row jsonb;
  v_child jsonb;
  v_grandchild jsonb;
begin
  select * into v_trash from public.trash where id = p_trash_id;
  if not found then
    raise exception 'Trash item not found';
  end if;

  v_row := v_trash.snapshot->'row';

  execute format(
    'insert into public.%I select * from jsonb_populate_record(null::public.%I, $1)',
    v_trash.entity_table, v_trash.entity_table
  ) using v_row;

  for v_child in select * from jsonb_array_elements(coalesce(v_trash.snapshot->'children', '[]'::jsonb))
  loop
    if jsonb_array_length(coalesce(v_child->'rows', '[]'::jsonb)) > 0 then
      execute format(
        'insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)',
        v_child->>'table', v_child->>'table'
      ) using (v_child->'rows');
    end if;

    for v_grandchild in select * from jsonb_array_elements(coalesce(v_child->'children', '[]'::jsonb))
    loop
      if jsonb_array_length(coalesce(v_grandchild->'rows', '[]'::jsonb)) > 0 then
        execute format(
          'insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)',
          v_grandchild->>'table', v_grandchild->>'table'
        ) using (v_grandchild->'rows');
      end if;
    end loop;
  end loop;

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by)
  values ('restore', v_trash.entity_table, v_trash.entity_id, v_trash.entity_label,
    format('Restored %s %s from Trash', v_trash.entity_table, coalesce(v_trash.entity_label, v_trash.entity_id)), p_performed_by);

  delete from public.trash where id = p_trash_id;
end;
$$;

grant execute on function public.restore_trash_item(bigint, text) to authenticated;

create or replace function public.purge_trash_item(p_trash_id bigint, p_performed_by text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trash public.trash%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Only admins can permanently delete trash items';
  end if;

  select * into v_trash from public.trash where id = p_trash_id;
  if not found then
    raise exception 'Trash item not found';
  end if;

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by)
  values ('delete', 'trash_item', v_trash.entity_id, v_trash.entity_label,
    format('Permanently deleted %s %s from Trash', v_trash.entity_table, coalesce(v_trash.entity_label, v_trash.entity_id)), p_performed_by);

  delete from public.trash where id = p_trash_id;
end;
$$;

grant execute on function public.purge_trash_item(bigint, text) to authenticated;

create or replace function public.purge_expired_trash()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.trash where purge_at < now();
end;
$$;

grant execute on function public.purge_expired_trash() to authenticated;


