-- ==========================================
-- 1. Create Tables
-- ==========================================

-- Profiles (linked to auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  role text not null check (role in ('admin', 'user')),
  full_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inventory
create table public.inventory (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null check (type in ('manufactured', 'resell', 'waste')),
  quantity integer not null default 0,
  price_per_cube numeric(10, 2),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Customers
create table public.customers (
  id bigint generated by default as identity primary key,
  customer_code text not null unique,
  name text not null,
  whatsapp_number text not null unique,
  address text default '',
  email text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Sales
create table public.sales (
  id bigint generated by default as identity primary key,
  sale_code text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  quantity integer not null,
  price_per_cube numeric(10, 2) not null,
  total_amount numeric(10, 2) not null,
  payment_type text not null check (payment_type in ('cash', 'debt')),
  bill_pdf_url text,
  sale_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text not null
);

-- Debts
create table public.debts (
  id bigint generated by default as identity primary key,
  sale_id bigint references public.sales(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  total_amount numeric(10, 2) not null,
  paid_amount numeric(10, 2) not null default 0,
  remaining_amount numeric(10, 2) not null,
  status text not null check (status in ('pending', 'partial', 'settled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Debt Settlements
create table public.debt_settlements (
  id bigint generated by default as identity primary key,
  debt_id bigint references public.debts(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete cascade,
  amount_paid numeric(10, 2) not null,
  settlement_date timestamp with time zone default timezone('utc'::text, now()) not null,
  bill_pdf_url text,
  created_by text not null
);

-- Settings
create table public.settings (
  id bigint generated by default as identity primary key,
  company_name text not null default 'Sagacious Ice Factory',
  company_address text default '',
  company_phone text default '',
  company_email text default '',
  logo_url text,
  favicon_url text,
  gemini_api_key text default '',
  ai_enabled boolean default true,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Code Counters (Atomic Sequential Code Generator)
create table if not exists public.code_counters (
  entity text primary key,
  last_value bigint not null default 0
);

-- Inventory Transactions Audit Log
create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  inventory_id bigint references public.inventory(id) on delete cascade,
  transaction_type text not null check (transaction_type in ('add', 'sale_deduction', 'manual_removal', 'adjustment')),
  quantity_change integer not null,
  previous_quantity integer not null,
  new_quantity integer not null,
  reference_code text default '',
  created_by text default 'System',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 2. Seed Initial Data & Indexes
-- ==========================================

insert into public.inventory (code, type, quantity, price_per_cube) values
('MFC-0001', 'manufactured', 2450, 12.00),
('RSC-0001', 'resell', 1100, 18.50),
('WST-0001', 'waste', 120, null)
on conflict (code) do nothing;

insert into public.settings (company_name, company_address, company_phone, company_email) values
('Sagacious Ice Factory', '102 Industrial Zone, Colombo, Sri Lanka', '0771234567', 'info@sagaciousice.com')
on conflict do nothing;

insert into public.code_counters (entity, last_value) values
('sale', 0),
('customer', 0),
('settlement', 0)
on conflict (entity) do nothing;

-- Performance Database Indexes
create index if not exists idx_sales_customer_id on public.sales(customer_id);
create index if not exists idx_sales_sale_date on public.sales(sale_date);
create index if not exists idx_sales_payment_type on public.sales(payment_type);
create index if not exists idx_debts_customer_id on public.debts(customer_id);
create index if not exists idx_debts_status on public.debts(status);
create index if not exists idx_debt_settlements_debt_id on public.debt_settlements(debt_id);
create index if not exists idx_debt_settlements_customer_id on public.debt_settlements(customer_id);
create index if not exists idx_customers_whatsapp on public.customers(whatsapp_number);
create index if not exists idx_operating_expenses_category on public.operating_expenses(category);
create index if not exists idx_operating_expenses_date on public.operating_expenses(expense_date);
create index if not exists idx_production_batches_date on public.production_batches(batch_date);
create index if not exists idx_inventory_transactions_inv_id on public.inventory_transactions(inventory_id);

-- ==========================================
-- 3. Enable Row Level Security (RLS)
-- ==========================================

alter table public.profiles enable row level security;
alter table public.inventory enable row level security;
alter table public.customers enable row level security;
alter table public.sales enable row level security;
alter table public.debts enable row level security;
alter table public.debt_settlements enable row level security;
alter table public.settings enable row level security;
alter table public.code_counters enable row level security;
alter table public.inventory_transactions enable row level security;

-- ==========================================
-- 4. Create Helper & Atomic RPC Functions
-- ==========================================

-- Check if current user is an admin
create or replace function public.is_admin()
returns boolean as $$
begin
  return exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
end;
$$ language plpgsql security definer;

-- Atomic Sequential Code Generator
create or replace function public.get_next_code(p_entity text, p_prefix text)
returns text as $$
declare
  v_next bigint;
  v_date_suffix text;
begin
  insert into public.code_counters (entity, last_value)
  values (p_entity, 1)
  on conflict (entity) do update set last_value = public.code_counters.last_value + 1
  returning last_value into v_next;

  if p_entity = 'customer' then
    return p_prefix || '-' || lpad(v_next::text, 4, '0');
  else
    v_date_suffix := to_char(now(), 'DDMMYY');
    return p_prefix || '-' || v_next::text || '-' || v_date_suffix;
  end if;
end;
$$ language plpgsql security definer;

-- Atomic Inventory Add Stock
create or replace function public.add_inventory_stock(p_id bigint, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_prev_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select quantity into v_prev_qty
  from public.inventory
  where id = p_id
  for update;

  if not found then
    raise exception 'Inventory item not found';
  end if;

  v_new_qty := v_prev_qty + p_amount;
  
  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = p_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (p_id, 'add', p_amount, v_prev_qty, v_new_qty, 'STOCK_ADD', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Deduct Stock (By Item ID)
create or replace function public.deduct_inventory_stock(p_id bigint, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select quantity into v_current_qty
  from public.inventory
  where id = p_id
  for update;

  if not found then
    raise exception 'Inventory item not found';
  end if;

  if v_current_qty < p_amount then
    raise exception 'Insufficient stock. Available: %', v_current_qty;
  end if;

  v_new_qty := v_current_qty - p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = p_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (p_id, 'manual_removal', -p_amount, v_current_qty, v_new_qty, 'MANUAL_REMOVE', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Add Stock (By Cube Type)
-- Row-locked mirror of deduct_inventory_stock_by_type, used wherever stock is
-- added by cube type rather than by a known inventory row id (e.g. production
-- batches crediting Manufactured Cubes). Prevents the lost-update race where
-- two concurrent adds both read the same starting quantity.
create or replace function public.add_inventory_stock_by_type(p_cube_type text, p_amount integer, p_reference_code text default 'STOCK_ADD', p_created_by text default 'Operator')
returns void as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select id, quantity into v_item_id, v_current_qty
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then
    raise exception 'Inventory item for % not found', p_cube_type;
  end if;

  v_new_qty := v_current_qty + p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = v_item_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (v_item_id, 'add', p_amount, v_current_qty, v_new_qty, p_reference_code, p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Inventory Deduct Stock (By Cube Type)
create or replace function public.deduct_inventory_stock_by_type(p_cube_type text, p_amount integer, p_created_by text default 'Operator')
returns void as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_new_qty integer;
begin
  if p_amount <= 0 then
    raise exception 'Amount must be a positive integer';
  end if;

  select id, quantity into v_item_id, v_current_qty
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then
    raise exception 'Inventory item for % not found', p_cube_type;
  end if;

  if v_current_qty < p_amount then
    raise exception 'Insufficient stock. Available: %', v_current_qty;
  end if;

  v_new_qty := v_current_qty - p_amount;

  update public.inventory
  set quantity = v_new_qty,
      updated_at = timezone('utc'::text, now())
  where id = v_item_id;

  insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
  values (v_item_id, 'sale_deduction', -p_amount, v_current_qty, v_new_qty, 'SALE_DEDUCTION', p_created_by);
end;
$$ language plpgsql security definer;

-- Atomic Transactional Order Placement Function
-- SECURITY NOTE: the sale price is never trusted from the client. It is always
-- read from the locked inventory row; a caller-supplied price is only honored
-- when the caller is an admin (Key Business Rule: "price per cube editable by
-- admin only"). This closes the gap where a non-admin (or a direct RPC call)
-- could previously submit an arbitrary price_per_cube and have it accepted.
--
-- CASH-TO-OLD-DEBT OFFSET: when this is a 'cash' order and the customer has
-- any pre-existing outstanding debt(s), the incoming cash is first applied
-- FIFO (oldest debt first) to reduce that old debt before it counts toward
-- this sale. Whatever portion of THIS sale's own cost isn't covered by
-- whatever cash is left over becomes a new debt for this sale (and the sale
-- is recorded as payment_type='debt' in that case, since only part or none
-- of its own price was actually paid at time of purchase). A 'debt' (credit)
-- order is unaffected by this and always creates its own independent debt,
-- exactly as before — this behavior only triggers on cash payments.
--
-- Example: customer owes 50,000 (old debt). Places a new 25,000 cash order.
-- The 25,000 cash is applied to the old debt first -> old debt drops to
-- 25,000. Nothing is left to cover the new order's own 25,000 cost, so a
-- fresh 25,000 debt is created for THIS sale (dated today, ages independently
-- of the old one).
create or replace function public.place_order_transaction(
  p_customer_id bigint,
  p_cube_type text,
  p_quantity integer,
  p_price_per_cube numeric,
  p_payment_type text,
  p_created_by text
) returns jsonb as $$
declare
  v_item_id bigint;
  v_current_qty integer;
  v_inventory_price numeric(10, 2);
  v_final_price numeric(10, 2);
  v_new_qty integer;
  v_sale_code text;
  v_total_amount numeric(10, 2);
  v_sale_id bigint;
  v_debt_id bigint := null;
  v_now timestamp with time zone := timezone('utc'::text, now());
  v_final_payment_type text := p_payment_type;
  v_cash_remaining numeric(10, 2);
  v_applied_to_old_debt numeric(10, 2) := 0;
  v_old_debt record;
  v_apply_amt numeric(10, 2);
  v_old_new_remaining numeric(10, 2);
  v_old_new_status text;
  v_settlement_code text;
  v_sale_paid_portion numeric(10, 2);
  v_sale_shortfall numeric(10, 2) := 0;
begin
  -- Validate inputs
  if p_customer_id is null then raise exception 'Customer is required'; end if;
  if p_quantity <= 0 then raise exception 'Quantity must be a positive integer'; end if;
  if p_payment_type not in ('cash', 'debt') then raise exception 'Invalid payment type'; end if;

  -- 1. Lock inventory row and read the authoritative price + stock
  select id, quantity, price_per_cube into v_item_id, v_current_qty, v_inventory_price
  from public.inventory
  where type = p_cube_type
  for update;

  if not found then raise exception 'Inventory item for % not found', p_cube_type; end if;
  if v_current_qty < p_quantity then raise exception 'Insufficient stock. Available: %', v_current_qty; end if;
  if v_inventory_price is null or v_inventory_price <= 0 then
    raise exception 'Price per cube must be set before placing a sale';
  end if;

  -- Non-admins (and any caller not supplying a price) always sell at the
  -- current inventory price. Admins may override with a caller-supplied
  -- positive price (e.g. a negotiated discount).
  if public.is_admin() and p_price_per_cube is not null and p_price_per_cube > 0 then
    v_final_price := p_price_per_cube;
  else
    v_final_price := v_inventory_price;
  end if;

  v_new_qty := v_current_qty - p_quantity;

  -- 2. Deduct inventory stock
  update public.inventory
  set quantity = v_new_qty,
      updated_at = v_now
  where id = v_item_id;

  -- 3. Atomic sale code generation
  v_sale_code := public.get_next_code('sale', 'S');
  v_total_amount := v_final_price * p_quantity;
  v_sale_paid_portion := v_total_amount;

  -- 4. Cash-to-old-debt FIFO offset (cash orders only)
  if p_payment_type = 'cash' then
    v_cash_remaining := v_total_amount;

    for v_old_debt in
      select id, remaining_amount
      from public.debts
      where customer_id = p_customer_id
        and status in ('pending', 'partial')
      order by created_at asc
      for update
    loop
      exit when v_cash_remaining <= 0;

      v_apply_amt := least(v_cash_remaining, v_old_debt.remaining_amount);
      v_old_new_remaining := v_old_debt.remaining_amount - v_apply_amt;
      v_old_new_status := case when v_old_new_remaining <= 0 then 'settled' else 'partial' end;

      update public.debts
      set paid_amount = paid_amount + v_apply_amt,
          remaining_amount = v_old_new_remaining,
          status = v_old_new_status
      where id = v_old_debt.id;

      v_settlement_code := public.get_next_code('settlement', 'D');
      insert into public.debt_settlements (debt_id, customer_id, amount_paid, settlement_date, created_by)
      values (v_old_debt.id, p_customer_id, v_apply_amt, v_now, p_created_by || ' (auto-applied from sale ' || v_sale_code || ')');

      v_applied_to_old_debt := v_applied_to_old_debt + v_apply_amt;
      v_cash_remaining := v_cash_remaining - v_apply_amt;
    end loop;

    v_sale_paid_portion := v_cash_remaining;
    v_sale_shortfall := v_total_amount - v_cash_remaining;

    if v_sale_shortfall > 0 then
      v_final_payment_type := 'debt';
    end if;
  end if;

  -- 5. Create sale record (payment_type reflects the actual outcome)
  insert into public.sales (
    sale_code, customer_id, cube_type, quantity, price_per_cube, total_amount, payment_type, sale_date, created_by
  ) values (
    v_sale_code, p_customer_id, p_cube_type, p_quantity, v_final_price, v_total_amount, v_final_payment_type, v_now, p_created_by
  ) returning id into v_sale_id;

  -- 6. Record inventory audit log
  insert into public.inventory_transactions (
    inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by
  ) values (
    v_item_id, 'sale_deduction', -p_quantity, v_current_qty, v_new_qty, v_sale_code, p_created_by
  );

  -- 7. Create a debt for this sale if applicable
  if p_payment_type = 'debt' then
    -- Original behavior: a plain credit order, no cash involved at all.
    insert into public.debts (
      sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at
    ) values (
      v_sale_id, p_customer_id, v_total_amount, 0, v_total_amount, 'pending', v_now
    ) returning id into v_debt_id;
  elsif v_sale_shortfall > 0 then
    -- Cash order whose payment was (fully or partly) redirected to older
    -- debt, leaving this sale itself partly or fully unpaid.
    insert into public.debts (
      sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at
    ) values (
      v_sale_id, p_customer_id, v_total_amount, v_sale_paid_portion, v_sale_shortfall,
      case when v_sale_paid_portion <= 0 then 'pending' else 'partial' end, v_now
    ) returning id into v_debt_id;
  end if;

  return jsonb_build_object(
    'id', v_sale_id,
    'sale_code', v_sale_code,
    'customer_id', p_customer_id,
    'cube_type', p_cube_type,
    'quantity', p_quantity,
    'price_per_cube', v_final_price,
    'total_amount', v_total_amount,
    'payment_type', v_final_payment_type,
    'sale_date', v_now,
    'debt_id', v_debt_id,
    'applied_to_old_debt', v_applied_to_old_debt,
    'new_debt_amount', v_sale_shortfall
  );
end;
$$ language plpgsql security definer;

-- Atomic Debt Settlement Transaction
-- Locks the debt row so two concurrent/duplicate settlements can never both
-- apply against the same "remaining_amount" snapshot (fixes lost-payment
-- race), and updates the debt + inserts the audit row in one transaction so
-- a failure can never leave the debt updated without a matching settlement
-- record (fixes double-apply-on-retry).
create or replace function public.settle_debt_transaction(
  p_debt_id bigint,
  p_amount_paid numeric,
  p_created_by text
) returns jsonb as $$
declare
  v_total numeric(10, 2);
  v_paid numeric(10, 2);
  v_remaining numeric(10, 2);
  v_customer_id bigint;
  v_sale_id bigint;
  v_new_paid numeric(10, 2);
  v_new_remaining numeric(10, 2);
  v_new_status text;
  v_settlement_code text;
  v_settlement_id bigint;
  v_now timestamp with time zone := timezone('utc'::text, now());
begin
  if p_amount_paid is null or p_amount_paid <= 0 then
    raise exception 'Settlement amount must be a positive number';
  end if;

  select total_amount, paid_amount, remaining_amount, customer_id, sale_id
    into v_total, v_paid, v_remaining, v_customer_id, v_sale_id
  from public.debts
  where id = p_debt_id
  for update;

  if not found then
    raise exception 'Debt record not found';
  end if;

  if p_amount_paid > v_remaining then
    raise exception 'Payment exceeds outstanding debt. Max payable: LKR %', v_remaining;
  end if;

  v_new_paid := v_paid + p_amount_paid;
  v_new_remaining := v_total - v_new_paid;
  v_new_status := case when v_new_remaining <= 0 then 'settled' else 'partial' end;

  update public.debts
  set paid_amount = v_new_paid,
      remaining_amount = v_new_remaining,
      status = v_new_status
  where id = p_debt_id;

  v_settlement_code := public.get_next_code('settlement', 'D');

  insert into public.debt_settlements (
    debt_id, customer_id, amount_paid, settlement_date, created_by
  ) values (
    p_debt_id, v_customer_id, p_amount_paid, v_now, p_created_by
  ) returning id into v_settlement_id;

  return jsonb_build_object(
    'id', v_settlement_id,
    'settlement_code', v_settlement_code,
    'debt_id', p_debt_id,
    'customer_id', v_customer_id,
    'sale_id', v_sale_id,
    'amount_paid', p_amount_paid,
    'remaining_amount', v_new_remaining,
    'status', v_new_status,
    'settlement_date', v_now
  );
end;
$$ language plpgsql security definer;

-- Atomic Inventory Update Price
create or replace function public.update_inventory_price(p_id bigint, p_price numeric)
returns void as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update inventory prices';
  end if;
  
  if p_price <= 0 then
    raise exception 'Price must be a positive value';
  end if;

  update public.inventory
  set price_per_cube = p_price,
      updated_at = timezone('utc'::text, now())
  where id = p_id;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 5. Tightened RLS Policies Definition
-- ==========================================

-- Profiles policies
create policy "Allow read profiles for authenticated" on public.profiles
  for select to authenticated using (true);

create policy "Allow update profiles for admins" on public.profiles
  for update to authenticated using (public.is_admin());

-- Inventory policies
create policy "Allow read inventory for authenticated" on public.inventory
  for select to authenticated using (true);

create policy "Allow admin write inventory" on public.inventory
  for all to authenticated using (public.is_admin());

-- Settings policies (authenticated read only, admin write)
create policy "Allow read settings for authenticated" on public.settings
  for select to authenticated using (true);

create policy "Allow write settings for admins" on public.settings
  for all to authenticated using (public.is_admin());

-- Code Counters policies
create policy "Allow read code_counters for authenticated" on public.code_counters
  for select to authenticated using (true);

create policy "Allow update code_counters for authenticated" on public.code_counters
  for all to authenticated using (true);

-- Customers policies
create policy "Allow read customers for authenticated" on public.customers
  for select to authenticated using (true);

create policy "Allow insert customers for authenticated" on public.customers
  for insert to authenticated with check (true);

create policy "Allow update customers for admins" on public.customers
  for update to authenticated using (public.is_admin());

create policy "Allow delete customers for admins" on public.customers
  for delete to authenticated using (public.is_admin());

-- Sales policies
create policy "Allow read sales for authenticated" on public.sales
  for select to authenticated using (true);

create policy "Allow insert sales for authenticated" on public.sales
  for insert to authenticated with check (true);

create policy "Allow update sales for admins" on public.sales
  for update to authenticated using (public.is_admin());

create policy "Allow delete sales for admins" on public.sales
  for delete to authenticated using (public.is_admin());

-- Debts policies
create policy "Allow read debts for authenticated" on public.debts
  for select to authenticated using (true);

create policy "Allow insert debts for authenticated" on public.debts
  for insert to authenticated with check (true);

create policy "Allow update debts for authenticated" on public.debts
  for update to authenticated using (true);

create policy "Allow delete debts for admins" on public.debts
  for delete to authenticated using (public.is_admin());

-- Debt Settlements policies
create policy "Allow read settlements for authenticated" on public.debt_settlements
  for select to authenticated using (true);

create policy "Allow insert settlements for authenticated" on public.debt_settlements
  for insert to authenticated with check (true);

create policy "Allow delete settlements for admins" on public.debt_settlements
  for delete to authenticated using (public.is_admin());

-- ==========================================
-- 6. Trigger to Create Profile on User Signup
-- ==========================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce(new.raw_user_meta_data->>'role', 'user')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Production Batches (Freezing & Energy Consumption)
create table if not exists public.production_batches (
  id bigint generated by default as identity primary key,
  batch_code text not null unique,
  cubes_produced integer not null default 0,
  electricity_units numeric(10, 2) default 0,
  electricity_cost numeric(10, 2) default 0,
  diesel_liters numeric(10, 2) default 0,
  diesel_cost numeric(10, 2) default 0,
  total_energy_cost numeric(10, 2) not null,
  cost_per_cube numeric(10, 4) not null,
  batch_date timestamp with time zone default timezone('utc'::text, now()) not null,
  notes text default '',
  created_by text default 'Operator'
);

-- Equipment Maintenance & Downtime
create table if not exists public.equipment_maintenance (
  id bigint generated by default as identity primary key,
  equipment_name text not null,
  equipment_type text not null default 'Machinery',
  status text not null check (status in ('operational', 'maintenance_due', 'offline')),
  last_service_date timestamp with time zone,
  next_service_due timestamp with time zone,
  cost numeric(10, 2) default 0,
  performed_by text default '',
  notes text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Operating Expenses Ledger
create table if not exists public.operating_expenses (
  id bigint generated by default as identity primary key,
  expense_code text not null unique,
  category text not null check (category in ('electricity', 'diesel', 'maintenance', 'salaries', 'water_utilities', 'packaging', 'other')),
  description text not null,
  amount numeric(10, 2) not null,
  payment_method text not null check (payment_method in ('cash', 'bank_transfer', 'cheque')),
  expense_date timestamp with time zone default timezone('utc'::text, now()) not null,
  created_by text default 'Admin'
);

-- Seed Initial Data for Equipment & Expenses
insert into public.equipment_maintenance (equipment_name, equipment_type, status, last_service_date, next_service_due, cost, performed_by, notes) values
('Industrial Compressor #1 (Sabroe 108)', 'Compressor', 'operational', '2026-07-10 00:00:00+00', '2026-08-10 00:00:00+00', 450.00, 'FrostTech Ltd', 'Routine oil filter replacement'),
('Ammonia Chiller Unit A', 'Chiller', 'maintenance_due', '2026-06-15 00:00:00+00', '2026-07-30 00:00:00+00', 0.00, 'Pending Tech', 'Pressure valve check required'),
('Backup Diesel Generator (150 kVA)', 'Generator', 'operational', '2026-07-01 00:00:00+00', '2026-09-01 00:00:00+00', 120.00, 'In-house Eng', 'Full tank refilled & load test passed'),
('RO Water Filtration Plant', 'Water System', 'offline', '2026-05-20 00:00:00+00', '2026-07-20 00:00:00+00', 0.00, 'AquaPure Services', 'Membrane replacement overdue')
on conflict do nothing;

insert into public.production_batches (batch_code, cubes_produced, electricity_units, electricity_cost, diesel_liters, diesel_cost, total_energy_cost, cost_per_cube, batch_date, notes) values
('BATCH-20260801-01', 1200, 180.5, 3610.00, 15.0, 1200.00, 4810.00, 4.0083, '2026-08-01 08:00:00+00', 'Morning Shift Freezing Cycle 1'),
('BATCH-20260731-02', 1500, 210.0, 4200.00, 0.0, 0.00, 4200.00, 2.8000, '2026-07-31 14:00:00+00', 'Full Grid Power Run')
on conflict do nothing;

insert into public.operating_expenses (expense_code, category, description, amount, payment_method, expense_date, created_by) values
('EXP-001-26', 'electricity', 'Monthly Industrial Power Bill - CEB', 45000.00, 'bank_transfer', '2026-07-28 00:00:00+00', 'Admin'),
('EXP-002-26', 'diesel', 'Bulk Diesel Refill for Generator', 15000.00, 'cash', '2026-07-29 00:00:00+00', 'Operator'),
('EXP-003-26', 'salaries', 'Plant Staff Weekly Wages', 32000.00, 'bank_transfer', '2026-07-31 00:00:00+00', 'Admin'),
('EXP-004-26', 'packaging', 'Heavy Duty Ice Bag Rolls (5000 units)', 18500.00, 'cheque', '2026-07-25 00:00:00+00', 'Admin')
on conflict do nothing;

alter table public.production_batches enable row level security;
alter table public.equipment_maintenance enable row level security;
alter table public.operating_expenses enable row level security;

create policy "Allow read production_batches" on public.production_batches for select to authenticated using (true);
create policy "Allow write production_batches" on public.production_batches for all to authenticated using (true);

create policy "Allow read equipment_maintenance" on public.equipment_maintenance for select to authenticated using (true);
create policy "Allow write equipment_maintenance" on public.equipment_maintenance for all to authenticated using (true);

create policy "Allow read operating_expenses" on public.operating_expenses for select to authenticated using (true);
create policy "Allow write operating_expenses" on public.operating_expenses for all to authenticated using (true);

-- ==========================================
-- 8. Supabase Storage Bucket & Private Bills Storage Setup
-- ==========================================

-- Create private storage bucket 'bills' (public = false)
insert into storage.buckets (id, name, public)
values ('bills', 'bills', false)
on conflict (id) do update set public = false;

-- Storage policies for private bucket 'bills' (Authenticated only)
drop policy if exists "Public Access to Bills" on storage.objects;
drop policy if exists "Authenticated Access to Bills" on storage.objects;
create policy "Authenticated Access to Bills" on storage.objects
  for select to authenticated using (bucket_id = 'bills');

drop policy if exists "Allow Insert Bills for Authenticated & Public" on storage.objects;
create policy "Allow Insert Bills for Authenticated" on storage.objects
  for insert to authenticated with check (bucket_id = 'bills');

drop policy if exists "Allow Delete Bills for Authenticated" on storage.objects;
create policy "Allow Delete Bills for Authenticated" on storage.objects
  for delete to authenticated using (bucket_id = 'bills');

-- Function to purge PDF bills created > 24 hours ago
create or replace function public.purge_expired_pdf_bills()
returns void as $$
begin
  -- Delete storage objects in bucket 'bills' older than 24 hours
  delete from storage.objects
  where bucket_id = 'bills'
    and created_at < (now() - interval '24 hours');
    
  -- Reset bill_pdf_url on sales older than 24 hours
  update public.sales
  set bill_pdf_url = null
  where sale_date < (now() - interval '24 hours')
    and bill_pdf_url is not null;
end;
$$ language plpgsql security definer;

-- ==========================================
-- 9. Daily Manager Reports Table Setup
-- ==========================================

create table if not exists public.daily_manager_reports (
  id bigint generated by default as identity primary key,
  report_date date not null unique,
  brine_cubes integer default 0,
  free_issue integer default 0,
  damaged_cubes integer default 0,
  pm_production_qty integer default 0,
  other_receipts numeric(10, 2) default 0,
  bank_deposit_amount numeric(10, 2) default 0,
  bank_deposit_today numeric(10, 2) default 0,
  cash_on_hand numeric(10, 2) default 0,
  cheques_on_hand numeric(10, 2) default 0,
  employee_logs jsonb default '[]'::jsonb,
  vehicle_logs jsonb default '[]'::jsonb,
  cheque_entries jsonb default '[]'::jsonb,
  withdrawals jsonb default '[]'::jsonb,
  other_details text default '',

  verified_by text default '',
  verified_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS bank_deposit_today NUMERIC(10, 2) DEFAULT 0;
ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS cheque_entries JSONB DEFAULT '[]'::jsonb;
ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS withdrawals JSONB DEFAULT '[]'::jsonb;
-- Day-scoped counter: how much of today's bank deposits came specifically
-- from physical cash (as opposed to cheques). Used only to compute the
-- suggested/default cash-on-hand figure for a day before the manager has
-- manually confirmed it — kept separate from bank_deposit_amount (the true
-- running bank balance) so a cheque deposit never wrongly reduces the
-- calculated cash balance.
ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS cash_deposited_today NUMERIC(10, 2) DEFAULT 0;
-- Explicit flag: has cash_on_hand actually been confirmed by a real action
-- (manual save, bank deposit, cash withdrawal) for this day, as opposed to
-- just holding the JS default of 0? Without this, a deliberately-saved
-- cash_on_hand of exactly 0 (e.g. "we banked everything, till is empty") is
-- indistinguishable from "nobody has entered anything yet" and gets silently
-- replaced by the auto-calculated suggestion.
ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS cash_on_hand_confirmed BOOLEAN DEFAULT false;
-- Same "explicitly entered vs still the JS default" problem as
-- cash_on_hand_confirmed, but for Section 01's brine (waste) cube count: a
-- manager typing 0 to correct an auto-calculated figure was previously
-- indistinguishable from the field never having been touched.
ALTER TABLE public.daily_manager_reports ADD COLUMN IF NOT EXISTS brine_cubes_confirmed BOOLEAN DEFAULT false;

alter table public.daily_manager_reports enable row level security;
create policy "Allow read daily_manager_reports" on public.daily_manager_reports for select to authenticated using (true);
create policy "Allow write daily_manager_reports" on public.daily_manager_reports for all to authenticated using (true);





