-- Multi-item single-bill orders (SalesTab.md: "if I use two types of items
-- (Production and Resell) both in one order, it should save as a single
-- bill with two types of items in two rows").
--
-- Today the New Order wizard's "+Add Row" places one separate `sales` row
-- (one sale_code) PER ROW. This migration adds a `sale_items` line-items
-- table so a single order with multiple cube types produces ONE sale_code
-- with multiple item rows.
--
-- Backward compatibility: `sales.cube_type`/`sales.price_per_cube` become
-- nullable and are populated ONLY when the whole order reduces to exactly
-- one (cube_type, price_per_cube) pair across all its items — the common,
-- pre-existing single-row case. `sales.quantity` stays not-null and is
-- always the sum of item quantities (unchanged value for single-item
-- orders). Every historical sale is backfilled with one mirroring
-- `sale_items` row so type-aware reporting can always read from
-- `sale_items` uniformly going forward.

-- 1. Line items table
create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  quantity integer not null check (quantity > 0),
  price_per_cube numeric(10, 2) not null check (price_per_cube > 0),
  subtotal numeric(10, 2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_sale_items_sale_id on public.sale_items(sale_id);

alter table public.sale_items enable row level security;

create policy "Allow read sale_items for authenticated" on public.sale_items
  for select to authenticated using (true);

create policy "Allow insert sale_items for authenticated" on public.sale_items
  for insert to authenticated with check (true);

create policy "Allow update sale_items for admins" on public.sale_items
  for update to authenticated using (public.is_admin());

create policy "Allow delete sale_items for admins" on public.sale_items
  for delete to authenticated using (public.is_admin());

-- 2. Legacy scalar columns become nullable on `sales`
alter table public.sales alter column cube_type drop not null;
alter table public.sales alter column price_per_cube drop not null;

-- 3. Backfill: every existing sale gets one mirroring line item
insert into public.sale_items (sale_id, cube_type, quantity, price_per_cube, subtotal)
select s.id, s.cube_type, s.quantity, s.price_per_cube, s.total_amount
from public.sales s
where s.cube_type is not null
  and not exists (select 1 from public.sale_items si where si.sale_id = s.id);

-- 4. Atomic Multi-Item Order Placement Transaction
-- Same cash-to-old-debt FIFO offset and admin-price-override rules as
-- place_order_transaction (kept in place, unused after this migration —
-- left as a harmless additive no-op since nothing else calls it), just
-- generalized across a jsonb array of {cube_type, quantity, price_per_cube}
-- items instead of a single item. Since there are only ever two cube
-- types, inventory rows are locked in the fixed order manufactured-then-
-- resell (rather than a generic loop) to avoid deadlocking against
-- concurrent orders/edits touching both types.
create or replace function public.place_multi_item_order_transaction(
  p_customer_id bigint,
  p_items jsonb,
  p_payment_type text,
  p_created_by text
) returns jsonb as $$
declare
  v_item record;
  v_mfc_id bigint;
  v_mfc_qty integer;
  v_mfc_price numeric(10, 2);
  v_mfc_needed integer := 0;
  v_rsc_id bigint;
  v_rsc_qty integer;
  v_rsc_price numeric(10, 2);
  v_rsc_needed integer := 0;

  v_sale_code text;
  v_sale_id bigint;
  v_total_amount numeric(10, 2) := 0;
  v_now timestamp with time zone := timezone('utc'::text, now());
  v_resolved_price numeric(10, 2);
  v_item_subtotal numeric(10, 2);
  v_resolved_items jsonb := '[]'::jsonb;

  v_single_cube_type text;
  v_single_price numeric(10, 2);
  v_price_consistent boolean := true;

  v_debt_id bigint := null;
  v_cash_remaining numeric(10, 2);
  v_applied_to_old_debt numeric(10, 2) := 0;
  v_old_debt record;
  v_apply_amt numeric(10, 2);
  v_old_new_remaining numeric(10, 2);
  v_old_new_status text;
begin
  if p_customer_id is null then raise exception 'Customer is required'; end if;
  if p_payment_type not in ('cash', 'debt') then raise exception 'Invalid payment type'; end if;
  if p_items is null or jsonb_array_length(p_items) = 0 then raise exception 'At least one order item is required'; end if;

  -- 1. Validate items and tally the requested quantity per cube type
  for v_item in select * from jsonb_to_recordset(p_items) as x(cube_type text, quantity integer, price_per_cube numeric) loop
    if v_item.cube_type not in ('manufactured', 'resell') then raise exception 'Invalid cube type selected'; end if;
    if v_item.quantity is null or v_item.quantity <= 0 then raise exception 'All row quantities must be positive integers'; end if;

    if v_item.cube_type = 'manufactured' then
      v_mfc_needed := v_mfc_needed + v_item.quantity;
    else
      v_rsc_needed := v_rsc_needed + v_item.quantity;
    end if;
  end loop;

  -- 2. Lock the inventory row(s) actually needed, in fixed alphabetical order
  if v_mfc_needed > 0 then
    select id, quantity, price_per_cube into v_mfc_id, v_mfc_qty, v_mfc_price
    from public.inventory where type = 'manufactured' for update;
    if not found then raise exception 'Inventory item for manufactured not found'; end if;
    if v_mfc_qty < v_mfc_needed then raise exception 'Insufficient Production stock. Available: %', v_mfc_qty; end if;
    if v_mfc_price is null or v_mfc_price <= 0 then raise exception 'Price per cube must be set before placing a sale'; end if;
  end if;

  if v_rsc_needed > 0 then
    select id, quantity, price_per_cube into v_rsc_id, v_rsc_qty, v_rsc_price
    from public.inventory where type = 'resell' for update;
    if not found then raise exception 'Inventory item for resell not found'; end if;
    if v_rsc_qty < v_rsc_needed then raise exception 'Insufficient Resell stock. Available: %', v_rsc_qty; end if;
    if v_rsc_price is null or v_rsc_price <= 0 then raise exception 'Price per cube must be set before placing a sale'; end if;
  end if;

  -- 3. Deduct the summed quantity per type
  if v_mfc_needed > 0 then
    update public.inventory set quantity = v_mfc_qty - v_mfc_needed, updated_at = v_now where id = v_mfc_id;
  end if;
  if v_rsc_needed > 0 then
    update public.inventory set quantity = v_rsc_qty - v_rsc_needed, updated_at = v_now where id = v_rsc_id;
  end if;

  -- 4. One sale_code for the whole order
  v_sale_code := public.get_next_code('sale', 'S');

  -- 5. Resolve each item's final price (admin override honored per item;
  --    everyone else gets the live inventory price for that item's cube
  --    type — same rule as place_order_transaction) and accumulate the total.
  for v_item in select * from jsonb_to_recordset(p_items) as x(cube_type text, quantity integer, price_per_cube numeric) loop
    if public.is_admin() and v_item.price_per_cube is not null and v_item.price_per_cube > 0 then
      v_resolved_price := v_item.price_per_cube;
    else
      v_resolved_price := case when v_item.cube_type = 'manufactured' then v_mfc_price else v_rsc_price end;
    end if;

    v_item_subtotal := v_resolved_price * v_item.quantity;
    v_total_amount := v_total_amount + v_item_subtotal;

    v_resolved_items := v_resolved_items || jsonb_build_object(
      'cube_type', v_item.cube_type,
      'quantity', v_item.quantity,
      'price_per_cube', v_resolved_price,
      'subtotal', v_item_subtotal
    );

    if v_single_cube_type is null then
      v_single_cube_type := v_item.cube_type;
      v_single_price := v_resolved_price;
    elsif v_single_cube_type <> v_item.cube_type or v_single_price <> v_resolved_price then
      v_price_consistent := false;
    end if;
  end loop;

  -- 6. Cash-to-old-debt FIFO offset (cash orders only) — identical logic to
  --    place_order_transaction, applied against the combined order total.
  if p_payment_type = 'cash' then
    v_cash_remaining := v_total_amount;

    for v_old_debt in
      select id, remaining_amount
      from public.debts
      where customer_id = p_customer_id
        and status in ('pending', 'partial')
      order by created_at asc
      for update
    loop
      exit when v_cash_remaining <= 0;

      v_apply_amt := least(v_cash_remaining, v_old_debt.remaining_amount);
      v_old_new_remaining := v_old_debt.remaining_amount - v_apply_amt;
      v_old_new_status := case when v_old_new_remaining <= 0 then 'settled' else 'partial' end;

      update public.debts
      set paid_amount     = paid_amount + v_apply_amt,
          remaining_amount = v_old_new_remaining,
          status          = v_old_new_status,
          created_at      = case when v_old_new_remaining > 0 then v_now else created_at end
      where id = v_old_debt.id;

      insert into public.debt_settlements (debt_id, customer_id, amount_paid, settlement_date, created_by)
      values (v_old_debt.id, p_customer_id, v_apply_amt, v_now,
              p_created_by || ' (auto-applied from sale ' || v_sale_code || ')');

      v_applied_to_old_debt := v_applied_to_old_debt + v_apply_amt;
      v_cash_remaining := v_cash_remaining - v_apply_amt;
    end loop;
  end if;

  -- 7. Insert the one sales header row. Legacy cube_type/price_per_cube are
  --    populated only when the whole order is a single (type, price) pair.
  insert into public.sales (
    sale_code, customer_id, cube_type, quantity, price_per_cube, total_amount, payment_type, sale_date, created_by
  ) values (
    v_sale_code, p_customer_id,
    case when v_price_consistent then v_single_cube_type else null end,
    v_mfc_needed + v_rsc_needed,
    case when v_price_consistent then v_single_price else null end,
    v_total_amount, p_payment_type, v_now, p_created_by
  ) returning id into v_sale_id;

  -- 8. Insert one sale_items row per input item
  for v_item in select * from jsonb_to_recordset(v_resolved_items) as y(cube_type text, quantity integer, price_per_cube numeric, subtotal numeric) loop
    insert into public.sale_items (sale_id, cube_type, quantity, price_per_cube, subtotal)
    values (v_sale_id, v_item.cube_type, v_item.quantity, v_item.price_per_cube, v_item.subtotal);
  end loop;

  -- 9. Inventory audit log, one row per type actually deducted
  if v_mfc_needed > 0 then
    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_mfc_id, 'sale_deduction', -v_mfc_needed, v_mfc_qty, v_mfc_qty - v_mfc_needed, v_sale_code, p_created_by);
  end if;
  if v_rsc_needed > 0 then
    insert into public.inventory_transactions (inventory_id, transaction_type, quantity_change, previous_quantity, new_quantity, reference_code, created_by)
    values (v_rsc_id, 'sale_deduction', -v_rsc_needed, v_rsc_qty, v_rsc_qty - v_rsc_needed, v_sale_code, p_created_by);
  end if;

  -- 10. Create a debt for this sale if it is a Debt Credit order (unchanged
  --     pattern — one debt row keyed by sale_id/total_amount, agnostic to
  --     item count).
  if p_payment_type = 'debt' then
    insert into public.debts (
      sale_id, customer_id, total_amount, paid_amount, remaining_amount, status, created_at
    ) values (
      v_sale_id, p_customer_id, v_total_amount, 0, v_total_amount, 'pending', v_now
    ) returning id into v_debt_id;
  end if;

  return jsonb_build_object(
    'id', v_sale_id,
    'sale_code', v_sale_code,
    'customer_id', p_customer_id,
    'total_amount', v_total_amount,
    'payment_type', p_payment_type,
    'sale_date', v_now,
    'debt_id', v_debt_id,
    'applied_to_old_debt', v_applied_to_old_debt
  );
end;
$$ language plpgsql security definer;
