-- Recent Actions: a system-wide audit trail. Every create/update/delete/
-- restore performed anywhere in the app writes one row here so admins can
-- see who did what, and when. Insert is open to any authenticated user
-- (everyone's actions get logged); reading and pruning the log is
-- admin-only, matching the Dashboard.md spec.

create table public.activity_log (
  id bigint generated by default as identity primary key,
  action text not null,
  entity_type text not null,
  entity_id text,
  entity_label text,
  description text not null,
  performed_by text not null,
  performed_by_role text,
  created_at timestamptz not null default timezone('utc', now())
);

create index idx_activity_log_created_at on public.activity_log(created_at desc);

alter table public.activity_log enable row level security;

create policy "Allow insert activity_log for authenticated" on public.activity_log
  for insert to authenticated with check (true);
create policy "Allow select activity_log for admins" on public.activity_log
  for select to authenticated using (public.is_admin());
create policy "Allow delete activity_log for admins" on public.activity_log
  for delete to authenticated using (public.is_admin());
