-- Expenses Tab Redesign: replace the flat operating_expenses ledger with
-- dynamic categories/expense-items plus a Cash Book grid (ledger rows x
-- per-item amounts). See ExpensesTab.md for the full UI/behavior spec this
-- schema supports. No data migration: operating_expenses is dropped as-is.

drop table if exists public.operating_expenses cascade;

create table if not exists public.expense_categories (
  id bigint generated by default as identity primary key,
  category_code text not null unique,
  name text not null unique,
  position integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.expense_items (
  id bigint generated by default as identity primary key,
  expense_code text not null unique,
  name text not null,
  category_id bigint not null references public.expense_categories(id) on delete cascade,
  position integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (category_id, name)
);

create table if not exists public.expense_ledger_rows (
  id bigint generated by default as identity primary key,
  entry_date date not null default current_date,
  description text not null default '',
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.expense_amounts (
  id bigint generated by default as identity primary key,
  ledger_row_id bigint not null references public.expense_ledger_rows(id) on delete cascade,
  expense_item_id bigint not null references public.expense_items(id) on delete cascade,
  amount numeric(12, 2) not null default 0 check (amount >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (ledger_row_id, expense_item_id)
);

create index if not exists idx_expense_items_category on public.expense_items(category_id);
create index if not exists idx_expense_amounts_ledger_row on public.expense_amounts(ledger_row_id);
create index if not exists idx_expense_amounts_item on public.expense_amounts(expense_item_id);
create index if not exists idx_expense_ledger_rows_date on public.expense_ledger_rows(entry_date);

alter table public.expense_categories enable row level security;
alter table public.expense_items enable row level security;
alter table public.expense_ledger_rows enable row level security;
alter table public.expense_amounts enable row level security;

create policy "Allow read expense_categories" on public.expense_categories for select to authenticated using (true);
create policy "Allow write expense_categories" on public.expense_categories for all to authenticated using (true);

create policy "Allow read expense_items" on public.expense_items for select to authenticated using (true);
create policy "Allow write expense_items" on public.expense_items for all to authenticated using (true);

create policy "Allow read expense_ledger_rows" on public.expense_ledger_rows for select to authenticated using (true);
create policy "Allow write expense_ledger_rows" on public.expense_ledger_rows for all to authenticated using (true);

create policy "Allow read expense_amounts" on public.expense_amounts for select to authenticated using (true);
create policy "Allow write expense_amounts" on public.expense_amounts for all to authenticated using (true);

-- Extend the shared code generator with 5-digit zero-padded codes for the
-- new expense category/item entities (CAT-00001 / EXP-00001), alongside the
-- existing customer (4-digit) and generic date-suffixed branches.
create or replace function public.get_next_code(p_entity text, p_prefix text)
returns text as $$
declare
  v_next bigint;
  v_date_suffix text;
begin
  insert into public.code_counters (entity, last_value)
  values (p_entity, 1)
  on conflict (entity) do update set last_value = public.code_counters.last_value + 1
  returning last_value into v_next;

  if p_entity = 'customer' then
    return p_prefix || '-' || lpad(v_next::text, 4, '0');
  elsif p_entity in ('expense_category', 'expense_item') then
    return p_prefix || '-' || lpad(v_next::text, 5, '0');
  else
    v_date_suffix := to_char(now(), 'DDMMYY');
    return p_prefix || '-' || v_next::text || '-' || v_date_suffix;
  end if;
end;
$$ language plpgsql security definer;
