-- New Vehicles Tab: vehicle registry + a per-vehicle trip history log
-- (Date, Distance Travelled, Start/End Odometer, Description), mirroring
-- the inventory_transactions audit-log pattern used for stock movements.

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_no text not null unique,
  vehicle_model text not null,
  vehicle_type text not null check (vehicle_type in ('lorry', 'pickup')),
  initial_odometer integer not null default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.vehicle_trips (
  id bigint generated by default as identity primary key,
  vehicle_id bigint references public.vehicles(id) on delete cascade,
  trip_date date not null default (timezone('utc'::text, now()))::date,
  start_odometer integer not null,
  end_odometer integer not null,
  distance_travelled integer generated always as (end_odometer - start_odometer) stored,
  description text default '',
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint vehicle_trips_odometer_order check (end_odometer >= start_odometer)
);

create index if not exists idx_vehicle_trips_vehicle_id on public.vehicle_trips(vehicle_id);
create index if not exists idx_vehicle_trips_trip_date on public.vehicle_trips(trip_date);

alter table public.vehicles enable row level security;
alter table public.vehicle_trips enable row level security;

create policy "Allow read vehicles for authenticated" on public.vehicles
  for select to authenticated using (true);
create policy "Allow insert vehicles for authenticated" on public.vehicles
  for insert to authenticated with check (true);
create policy "Allow update vehicles for admins" on public.vehicles
  for update to authenticated using (public.is_admin());
create policy "Allow delete vehicles for admins" on public.vehicles
  for delete to authenticated using (public.is_admin());

create policy "Allow read vehicle_trips for authenticated" on public.vehicle_trips
  for select to authenticated using (true);
create policy "Allow insert vehicle_trips for authenticated" on public.vehicle_trips
  for insert to authenticated with check (true);
create policy "Allow delete vehicle_trips for admins" on public.vehicle_trips
  for delete to authenticated using (public.is_admin());
