-- New Transport Tab: driver registry + trip log (start/end odometer, vehicle,
-- driver, status), mirroring the vehicles/vehicle_trips audit-log pattern.
-- No Employee tab exists yet, so drivers get their own minimal registry here
-- in place of the "linked to employee tab" reference in the spec.

create table if not exists public.drivers (
  id bigint generated by default as identity primary key,
  driver_name text not null unique,
  phone text default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.transport_trips (
  id bigint generated by default as identity primary key,
  vehicle_id bigint not null references public.vehicles(id) on delete cascade,
  driver_id bigint not null references public.drivers(id) on delete restrict,
  start_odometer integer not null,
  end_odometer integer,
  distance_travelled integer generated always as (
    case when end_odometer is not null then end_odometer - start_odometer else null end
  ) stored,
  start_datetime timestamp with time zone not null default now(),
  end_datetime timestamp with time zone,
  description text default '',
  end_description text default '',
  status text not null default 'ongoing' check (status in ('ongoing', 'completed')),
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint transport_trips_odometer_order check (end_odometer is null or end_odometer >= start_odometer)
);

create index if not exists idx_transport_trips_vehicle_id on public.transport_trips(vehicle_id);
create index if not exists idx_transport_trips_driver_id on public.transport_trips(driver_id);
create index if not exists idx_transport_trips_status on public.transport_trips(status);
create index if not exists idx_transport_trips_start_datetime on public.transport_trips(start_datetime);

alter table public.drivers enable row level security;
alter table public.transport_trips enable row level security;

create policy "Allow read drivers for authenticated" on public.drivers
  for select to authenticated using (true);
create policy "Allow insert drivers for authenticated" on public.drivers
  for insert to authenticated with check (true);
create policy "Allow update drivers for admins" on public.drivers
  for update to authenticated using (public.is_admin());
create policy "Allow delete drivers for admins" on public.drivers
  for delete to authenticated using (public.is_admin());

create policy "Allow read transport_trips for authenticated" on public.transport_trips
  for select to authenticated using (true);
create policy "Allow insert transport_trips for authenticated" on public.transport_trips
  for insert to authenticated with check (true);
create policy "Allow update transport_trips for authenticated" on public.transport_trips
  for update to authenticated using (true);
create policy "Allow delete transport_trips for admins" on public.transport_trips
  for delete to authenticated using (public.is_admin());
