-- New Employees Tab: employee registry + a per-employee attendance log
-- (Date, Start Time, End Time, Description), mirroring the vehicles/
-- vehicle_trips registry + audit-log pattern.
--
-- The spec's "Add New Employee Dialog Box" only lists ID/Name/NIC/Phone/
-- Address, but the "Employees Table" view also shows Job Type and Status
-- columns with no other place for them to come from — job_type/status are
-- added to the employees table as a reasonable inference, same precedent as
-- the "Add Trip" button inferred for the Vehicles tab.
--
-- The existing `drivers` table (added for the Transport tab) stood in for
-- this tab while it didn't exist yet; it is intentionally left as-is here,
-- not merged into `employees` automatically, since transport_trips already
-- references drivers.id and reconciling them is a separate decision.

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  employee_code text not null unique,
  name text not null,
  nic text not null unique,
  phone text default '',
  address text default '',
  job_type text default '',
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.employee_attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  attendance_date date not null default (timezone('utc'::text, now()))::date,
  start_time time,
  end_time time,
  description text default '',
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_employee_attendance_employee_id on public.employee_attendance(employee_id);
create index if not exists idx_employee_attendance_date on public.employee_attendance(attendance_date);

alter table public.employees enable row level security;
alter table public.employee_attendance enable row level security;

create policy "Allow read employees for authenticated" on public.employees
  for select to authenticated using (true);
create policy "Allow insert employees for authenticated" on public.employees
  for insert to authenticated with check (true);
create policy "Allow update employees for admins" on public.employees
  for update to authenticated using (public.is_admin());
create policy "Allow delete employees for admins" on public.employees
  for delete to authenticated using (public.is_admin());

create policy "Allow read employee_attendance for authenticated" on public.employee_attendance
  for select to authenticated using (true);
create policy "Allow insert employee_attendance for authenticated" on public.employee_attendance
  for insert to authenticated with check (true);
create policy "Allow update employee_attendance for authenticated" on public.employee_attendance
  for update to authenticated using (true);
create policy "Allow delete employee_attendance for admins" on public.employee_attendance
  for delete to authenticated using (public.is_admin());
