-- Per-customer custom cube prices. New Order checkout looks up a rate here
-- for the selected customer + cube type first; falls back to the live
-- inventory.price_per_cube when no override row exists for that pair.
-- Only admins may write custom prices; any authenticated staff can read them
-- (needed so the New Order wizard can resolve the rate for any operator).

create table if not exists public.customer_cube_prices (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete cascade,
  cube_type text not null check (cube_type in ('manufactured', 'resell')),
  price_per_cube numeric(10, 2) not null check (price_per_cube > 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint customer_cube_prices_customer_type_unique unique (customer_id, cube_type)
);

create index if not exists idx_customer_cube_prices_customer_id on public.customer_cube_prices(customer_id);

alter table public.customer_cube_prices enable row level security;

create policy "Allow read customer_cube_prices for authenticated" on public.customer_cube_prices
  for select to authenticated using (true);
create policy "Allow insert customer_cube_prices for admins" on public.customer_cube_prices
  for insert to authenticated with check (public.is_admin());
create policy "Allow update customer_cube_prices for admins" on public.customer_cube_prices
  for update to authenticated using (public.is_admin());
create policy "Allow delete customer_cube_prices for admins" on public.customer_cube_prices
  for delete to authenticated using (public.is_admin());
