-- 1. Link cheque receipts to the customer who wrote them.
--
-- cheque_records only ever stored a free-text `payer_name`, so a cheque could
-- not be tied back to the account it settles — the Customer tab had no idea a
-- cheque had been received. customer_id is nullable so genuinely anonymous
-- cheques stay recordable, and payer_name is kept as the on-cheque name (which
-- is not always the account name).
--
-- One-time (walk-in) customers work here exactly as registered ones do: they
-- are real customer rows, so a cheque from a walk-in links the same way.

alter table public.cheque_records
  add column if not exists customer_id bigint references public.customers(id) on delete set null;

create index if not exists idx_cheque_records_customer_id on public.cheque_records(customer_id);


-- 2. Opening balances ("Initial Collection").
--
-- Every balance in Cash & Bank is derived from the transactions the system has
-- recorded, which means the day the factory started using the app, all of its
-- balances began at zero — the cash already in the till, the money already in
-- the bank and the cheques already in hand were invisible. There was no way to
-- state "we began with this much".
--
-- One row per store of value, set once at go-live. Kept as its own table (not
-- a synthetic transaction) so an opening balance is never mistaken for
-- trading activity in the history or the reports.

create table if not exists public.opening_balances (
  id bigint generated by default as identity primary key,
  scope text not null unique check (scope in ('cash', 'bank', 'cheques')),
  amount numeric(12, 2) not null default 0 check (amount >= 0),
  bank_name text,
  as_of_date date not null default (timezone('utc'::text, now()))::date,
  note text default '',
  set_by text not null default 'Admin',
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

alter table public.opening_balances enable row level security;

create policy "Allow read opening_balances for authenticated" on public.opening_balances
  for select to authenticated using (true);

-- Opening balances move every headline figure in the system, so only an
-- administrator may set or change them.
create policy "Allow insert opening_balances for admins" on public.opening_balances
  for insert to authenticated with check (public.is_admin());

create policy "Allow update opening_balances for admins" on public.opening_balances
  for update to authenticated using (public.is_admin());

create policy "Allow delete opening_balances for admins" on public.opening_balances
  for delete to authenticated using (public.is_admin());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'opening_balances'
  ) then
    alter publication supabase_realtime add table public.opening_balances;
  end if;
end $$;
