-- Trash / recoverable deletes: a generic snapshot table plus a small set of
-- security-definer functions replace direct `.delete()` calls across the
-- app. Deleting a row now snapshots it (and its known cascade children,
-- since Postgres FKs still cascade-delete them for real) into `trash`,
-- where it can be restored for 7 days before being purged for good.
--
-- The functions run as security definer so they can write to `trash` /
-- `activity_log` and delete from any whitelisted source table regardless of
-- that table's own RLS policies, while still being safely callable by any
-- authenticated user (the whitelist below is the only thing that limits
-- what `soft_delete_row` can touch).

create table public.trash (
  id bigint generated by default as identity primary key,
  entity_table text not null,
  entity_id text not null,
  entity_label text,
  snapshot jsonb not null,
  deleted_by text not null,
  deleted_at timestamptz not null default timezone('utc', now()),
  purge_at timestamptz not null default timezone('utc', now()) + interval '7 days'
);

create index idx_trash_purge_at on public.trash(purge_at);

alter table public.trash enable row level security;

-- No insert/update/delete policies on purpose: every write happens through
-- the security-definer functions below, which run with owner privileges.
create policy "Allow select trash for admins" on public.trash
  for select to authenticated using (public.is_admin());

create or replace function public.soft_delete_row(
  p_table text,
  p_id bigint,
  p_deleted_by text,
  p_deleted_by_role text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_children jsonb := '[]'::jsonb;
  v_label text;
begin
  if p_table not in (
    'customers', 'sales', 'debts', 'notes', 'employees', 'vehicles',
    'bank_deposits', 'cheque_records', 'bank_withdrawals', 'cash_receives',
    'customer_cube_prices', 'employee_attendance', 'vehicle_trips',
    'transport_trips', 'expense_ledger_rows'
  ) then
    raise exception 'Table % is not allowed for soft delete', p_table;
  end if;

  execute format('select to_jsonb(t) from public.%I t where id = $1', p_table)
    into v_row using p_id;

  if v_row is null then
    raise exception 'Row not found in %', p_table;
  end if;

  -- Cascade children captured explicitly (not via dynamic FK discovery) so
  -- the recovery tree stays predictable and matches this schema's actual
  -- `on delete cascade` relationships.
  if p_table = 'sales' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'sale_items',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.sale_items t where t.sale_id = p_id), '[]'::jsonb)
    ));
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'debts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.debts t where t.sale_id = p_id), '[]'::jsonb),
      'children', coalesce((
        select jsonb_agg(jsonb_build_object(
          'table', 'debt_settlements',
          'rows', coalesce((select jsonb_agg(to_jsonb(s)) from public.debt_settlements s where s.debt_id = d.id), '[]'::jsonb)
        ))
        from public.debts d where d.sale_id = p_id
      ), '[]'::jsonb)
    ));
  elsif p_table = 'customers' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'debts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.debts t where t.customer_id = p_id), '[]'::jsonb),
      'children', coalesce((
        select jsonb_agg(jsonb_build_object(
          'table', 'debt_settlements',
          'rows', coalesce((select jsonb_agg(to_jsonb(s)) from public.debt_settlements s where s.debt_id = d.id), '[]'::jsonb)
        ))
        from public.debts d where d.customer_id = p_id
      ), '[]'::jsonb)
    ));
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'transport_trips',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.transport_trips t where t.customer_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'vehicles' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'vehicle_trips',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.vehicle_trips t where t.vehicle_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'employees' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'employee_attendance',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.employee_attendance t where t.employee_id = p_id), '[]'::jsonb)
    ));
  elsif p_table = 'expense_ledger_rows' then
    v_children := v_children || jsonb_build_array(jsonb_build_object(
      'table', 'expense_amounts',
      'rows', coalesce((select jsonb_agg(to_jsonb(t)) from public.expense_amounts t where t.ledger_row_id = p_id), '[]'::jsonb)
    ));
  end if;

  v_label := coalesce(
    v_row->>'customer_code', v_row->>'sale_code', v_row->>'employee_code',
    v_row->>'vehicle_no', v_row->>'expense_code', v_row->>'category_code',
    v_row->>'name', v_row->>'note_text', v_row->>'id'
  );

  insert into public.trash (entity_table, entity_id, entity_label, snapshot, deleted_by)
  values (p_table, p_id::text, v_label, jsonb_build_object('row', v_row, 'children', v_children), p_deleted_by);

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by, performed_by_role)
  values ('delete', p_table, p_id::text, v_label, format('Deleted %s %s', p_table, coalesce(v_label, p_id::text)), p_deleted_by, p_deleted_by_role);

  execute format('delete from public.%I where id = $1', p_table) using p_id;
end;
$$;

grant execute on function public.soft_delete_row(text, bigint, text, text) to authenticated;

create or replace function public.restore_trash_item(p_trash_id bigint, p_performed_by text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trash public.trash%rowtype;
  v_row jsonb;
  v_child jsonb;
  v_grandchild jsonb;
begin
  select * into v_trash from public.trash where id = p_trash_id;
  if not found then
    raise exception 'Trash item not found';
  end if;

  v_row := v_trash.snapshot->'row';

  execute format(
    'insert into public.%I select * from jsonb_populate_record(null::public.%I, $1)',
    v_trash.entity_table, v_trash.entity_table
  ) using v_row;

  for v_child in select * from jsonb_array_elements(coalesce(v_trash.snapshot->'children', '[]'::jsonb))
  loop
    if jsonb_array_length(coalesce(v_child->'rows', '[]'::jsonb)) > 0 then
      execute format(
        'insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)',
        v_child->>'table', v_child->>'table'
      ) using (v_child->'rows');
    end if;

    for v_grandchild in select * from jsonb_array_elements(coalesce(v_child->'children', '[]'::jsonb))
    loop
      if jsonb_array_length(coalesce(v_grandchild->'rows', '[]'::jsonb)) > 0 then
        execute format(
          'insert into public.%I select * from jsonb_populate_recordset(null::public.%I, $1)',
          v_grandchild->>'table', v_grandchild->>'table'
        ) using (v_grandchild->'rows');
      end if;
    end loop;
  end loop;

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by)
  values ('restore', v_trash.entity_table, v_trash.entity_id, v_trash.entity_label,
    format('Restored %s %s from Trash', v_trash.entity_table, coalesce(v_trash.entity_label, v_trash.entity_id)), p_performed_by);

  delete from public.trash where id = p_trash_id;
end;
$$;

grant execute on function public.restore_trash_item(bigint, text) to authenticated;

create or replace function public.purge_trash_item(p_trash_id bigint, p_performed_by text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trash public.trash%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Only admins can permanently delete trash items';
  end if;

  select * into v_trash from public.trash where id = p_trash_id;
  if not found then
    raise exception 'Trash item not found';
  end if;

  insert into public.activity_log (action, entity_type, entity_id, entity_label, description, performed_by)
  values ('delete', 'trash_item', v_trash.entity_id, v_trash.entity_label,
    format('Permanently deleted %s %s from Trash', v_trash.entity_table, coalesce(v_trash.entity_label, v_trash.entity_id)), p_performed_by);

  delete from public.trash where id = p_trash_id;
end;
$$;

grant execute on function public.purge_trash_item(bigint, text) to authenticated;

-- Lazy purge: called opportunistically when the Trash page loads (this
-- project has no pg_cron scheduled job set up), so nothing recoverable
-- lingers past its 7-day window once an admin next opens the page.
create or replace function public.purge_expired_trash()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.trash where purge_at < now();
end;
$$;

grant execute on function public.purge_expired_trash() to authenticated;
