-- Notes and Messages Tab: a simple notes ledger where any authenticated
-- user can add timestamped notes visible to all staff.

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  note_text text not null,
  created_by text not null default 'Operator',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_notes_created_at on public.notes(created_at desc);

alter table public.notes enable row level security;

create policy "Allow read notes for authenticated" on public.notes
  for select to authenticated using (true);
create policy "Allow insert notes for authenticated" on public.notes
  for insert to authenticated with check (true);
create policy "Allow delete notes for admins" on public.notes
  for delete to authenticated using (public.is_admin());
