-- Cash & Bank Management redesign: replace the JSONB-in-one-row
-- (daily_manager_reports.cheque_entries / withdrawals, plus the single
-- cash_on_hand override) with four dedicated, permanent history ledgers.
-- See Cash&BankManagement.md for the full spec. daily_manager_reports keeps
-- its existing columns untouched (still used by the Daily Manager Report /
-- PDF); this migration only adds new tables alongside it.

create table if not exists public.cash_receives (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  receive_type text not null check (receive_type in ('head_office', 'other')),
  received_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.bank_deposits (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  cash_method text not null check (cash_method in ('sales', 'other', 'cheques')),
  bank_name text,
  deposited_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.cheque_records (
  id bigint generated by default as identity primary key,
  cheque_no text not null,
  bank_name text not null,
  amount numeric(12, 2) not null check (amount > 0),
  payer_name text not null,
  status text not null default 'pending' check (status in ('pending', 'deposited')),
  received_at timestamp with time zone not null default timezone('utc'::text, now()),
  deposited_at timestamp with time zone,
  deposit_id bigint references public.bank_deposits(id) on delete set null,
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.bank_withdrawals (
  id bigint generated by default as identity primary key,
  amount numeric(12, 2) not null check (amount > 0),
  bank_name text not null,
  purpose text not null,
  withdrawn_at timestamp with time zone not null default timezone('utc'::text, now()),
  created_by text default 'Admin',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_cash_receives_received_at on public.cash_receives(received_at);
create index if not exists idx_bank_deposits_deposited_at on public.bank_deposits(deposited_at);
create index if not exists idx_bank_deposits_bank_name on public.bank_deposits(bank_name);
create index if not exists idx_cheque_records_status on public.cheque_records(status);
create index if not exists idx_cheque_records_received_at on public.cheque_records(received_at);
create index if not exists idx_bank_withdrawals_withdrawn_at on public.bank_withdrawals(withdrawn_at);
create index if not exists idx_bank_withdrawals_bank_name on public.bank_withdrawals(bank_name);

alter table public.cash_receives enable row level security;
alter table public.bank_deposits enable row level security;
alter table public.cheque_records enable row level security;
alter table public.bank_withdrawals enable row level security;

create policy "Allow read cash_receives" on public.cash_receives for select to authenticated using (true);
create policy "Allow write cash_receives" on public.cash_receives for all to authenticated using (true);

create policy "Allow read bank_deposits" on public.bank_deposits for select to authenticated using (true);
create policy "Allow write bank_deposits" on public.bank_deposits for all to authenticated using (true);

create policy "Allow read cheque_records" on public.cheque_records for select to authenticated using (true);
create policy "Allow write cheque_records" on public.cheque_records for all to authenticated using (true);

create policy "Allow read bank_withdrawals" on public.bank_withdrawals for select to authenticated using (true);
create policy "Allow write bank_withdrawals" on public.bank_withdrawals for all to authenticated using (true);
