-- Notification log.
--
-- Sales invoices and debt-settlement receipts are sent to customers by
-- handing WhatsApp a pre-composed message. Nothing recorded that this had
-- happened, so there was no way to answer "was this customer notified, when,
-- and what were they told?". Every dispatch now writes a row here.
--
-- `message` stores the exact text handed to WhatsApp, so the record is an
-- accurate account of what the customer was told, not a reconstruction.

create table if not exists public.notification_log (
  id bigint generated by default as identity primary key,
  channel text not null default 'whatsapp' check (channel in ('whatsapp', 'sms', 'other')),
  notification_type text not null check (notification_type in ('sale_invoice', 'debt_settlement')),
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text,
  recipient_phone text,
  reference_code text,            -- sale_code or settlement_code
  amount numeric(12, 2),
  remaining_amount numeric(12, 2),
  payment_type text,
  message text not null,
  link_url text,
  sent_by text not null default 'Operator',
  sent_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_notification_log_customer_id on public.notification_log(customer_id);
create index if not exists idx_notification_log_sent_at on public.notification_log(sent_at desc);
create index if not exists idx_notification_log_type on public.notification_log(notification_type);

alter table public.notification_log enable row level security;

create policy "Allow read notification_log for authenticated" on public.notification_log
  for select to authenticated using (true);

create policy "Allow insert notification_log for authenticated" on public.notification_log
  for insert to authenticated with check (true);

create policy "Allow delete notification_log for admins" on public.notification_log
  for delete to authenticated using (public.is_admin());

-- Publish for realtime so the notification history refreshes live, like the
-- other ledgers.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notification_log'
  ) then
    alter publication supabase_realtime add table public.notification_log;
  end if;
end $$;
